/**
 * Python code map detectors (docs/codemap/CONTRACT.md §2, §2.1, §7; FIXTURES.md §4.1): SDK and
 * generated-client call sites, raw HTTP, widget templates, dynamic ids, keys, decoys, broken files. The
 * corpus tests compare every answer-key site of py-fastapi (and the Python part of the monorepo) by
 * (path, line, artifact, inputKeys, outputKeys); the keys are only read.
 */
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { detectProject } from '../src/codemap/detect.js';
import { DETECTORS as PY } from '../src/codemap/detectors/py/index.js';
import { DETECTORS as JAVA } from '../src/codemap/detectors/java/index.js';
import { initPythonParser } from '../src/codemap/detectors/py/parse.js';
import { DEFAULT_ENV_FILES } from '../src/codemap/walk.js';
import type { DetectContext, DetectedSite, Implementation, LockBinding } from '../src/codemap/types.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const CORPUS = join(HERE, 'fixtures', 'codemap');
const ENV_FILES = { secret: [...DEFAULT_ENV_FILES.secret, 'dot-env', 'dot-env.*'], names: [...DEFAULT_ENV_FILES.names, 'dot-env.example'] };
const NO_LOCKS: DetectContext = { locks: [], lockDir: null };

interface Run {
  sites: DetectedSite[];
  implementations: Implementation[];
  envVarNames: string[];
}

/** Run every Python detector over one in-memory file and gather what they report. */
function run(text: string, relPath = 'app/svc.py', ctx: DetectContext = NO_LOCKS): Run {
  const out: Run = { sites: [], implementations: [], envVarNames: [] };
  for (const d of PY) {
    const r = d.detect({ relPath, language: 'python', text }, ctx);
    out.sites.push(...r.sites);
    out.implementations.push(...r.implementations);
    out.envVarNames.push(...r.envVarNames);
  }
  out.sites.sort((a, b) => a.line - b.line);
  return out;
}

const SDK = 'from swfte import SwfteClient\nclient = SwfteClient()\n';

describe('py managed: SDK and typed client', () => {
  test('typed-client call carries alias, pinned version and contract hash from the lock', () => {
    const lock: LockBinding = {
      alias: 'lead-scoring',
      catalogRef: 'workflow:wf_Lead5Sc',
      language: 'python',
      pinnedVersion: '3',
      contractHash: 'h'.repeat(64),
      files: ['app/swfte_clients/lead_scoring.py'],
    };
    const src = [
      'from app.swfte_clients.lead_scoring import invoke_lead_scoring',
      '',
      'def score(company):',
      '    res = invoke_lead_scoring({"company": company, "domain": "x.io"})',
      '    return res["output"]["grade"]',
      '',
    ].join('\n');
    const r = run(src, 'app/services/lead_service.py', { locks: [lock], lockDir: '' });
    assert.equal(r.sites.length, 1);
    const s = r.sites[0]!;
    assert.deepEqual(
      { line: s.line, symbol: s.symbol, sdk: s.sdk, op: s.op, managed: s.managed, category: s.category, language: s.language },
      { line: 4, symbol: 'score', sdk: 'python', op: 'run', managed: 'typed-client', category: 'managed', language: 'python' },
    );
    assert.deepEqual(s.artifact, { kind: 'workflow', id: 'wf_Lead5Sc', unresolved: false, pinnedVersion: '3', alias: 'lead-scoring' });
    assert.equal(s.contractHash, 'h'.repeat(64));
    assert.deepEqual(s.inputKeys, ['company', 'domain']);
    assert.deepEqual(s.outputKeys, ['grade']);
    assert.equal(s.detector, 'py.managed');
  });

  test('the generated client itself reports an implementation and no call site', () => {
    const lock: LockBinding = { alias: 'lead-scoring', catalogRef: 'workflow:wf_Lead5Sc', language: 'python', pinnedVersion: null, contractHash: null, files: ['app/swfte_clients/lead_scoring.py'] };
    const src = [
      '# Generated by @swfte/mcp-server (swfte add). Do not edit by hand.',
      'import urllib.request',
      '',
      'def _call(url):',
      '    with urllib.request.urlopen(url) as res:',
      '        return res.read()',
      '',
      'def invoke_lead_scoring(inputs):',
      '    return _call("https://api.swfte.com/agents/v2/workflows/wf_Lead5Sc/invoke")',
      '',
    ].join('\n');
    const r = run(src, 'app/swfte_clients/lead_scoring.py', { locks: [lock], lockDir: '' });
    assert.deepEqual(r.sites, []);
    assert.deepEqual(r.implementations, [{ relPath: 'app/swfte_clients/lead_scoring.py', line: 5, alias: 'lead-scoring' }]);
  });

  test('SDK ops: run, chat, stream and read-output', () => {
    const src =
      SDK +
      [
        'def go(ag):',
        '    client.workflows.invoke_and_wait("wf_A", {"x": 1})',
        '    client.agents.chat("ag_B", "hello")',
        '    client.agents.chat_stream("ag_B", "hello")',
        '    client.workflows.get_execution_history("wf_A")',
        '',
      ].join('\n');
    const r = run(src);
    assert.deepEqual(
      r.sites.map((s) => [s.line, s.op, s.artifact.kind, s.artifact.id, s.artifact.alias, s.sdk, s.managed]),
      [
        [4, 'run', 'workflow', 'wf_A', null, 'python', 'typed-client'],
        [5, 'chat', 'agent', 'ag_B', null, 'python', 'typed-client'],
        [6, 'stream', 'agent', 'ag_B', null, 'python', 'typed-client'],
        [7, 'read-output', 'workflow', 'wf_A', null, 'python', 'typed-client'],
      ],
    );
    assert.deepEqual(r.sites[3]!.inputKeys, []);
    assert.deepEqual(r.sites[3]!.outputKeys, []);
  });

  test('a call shaped like the SDK in a file that never imports swfte is not a site', () => {
    const r = run('def f(client):\n    client.workflows.invoke("wf_A", {"x": 1})\n');
    assert.deepEqual(r.sites, []);
  });

  test('an SDK fork under another package name does not count', () => {
    const r = run('from acme_swfte_fork import SwfteClient\nc = SwfteClient()\n\ndef f():\n    c.workflows.invoke("wf_F", {"x": 1})\n');
    assert.deepEqual(r.sites, []);
  });
});

describe('py symbols, lines and dynamic ids', () => {
  test('symbol: lambda uses named ancestor, methods are Class.method, nested functions outer.inner', () => {
    const src =
      SDK +
      [
        'class Svc:',
        '    def go(self, xs):',
        '        return [client.workflows.invoke("wf_L", {"i": x}) for x in xs]',
        '',
        '    def lam(self):',
        '        f = lambda: client.agents.chat("ag_L", "hi")',
        '        return f',
        '',
        'def outer():',
        '    def inner():',
        '        return client.workflows.invoke("wf_N", {})',
        '    return inner',
        '',
        'client.workflows.invoke("wf_M", {})',
        '',
      ].join('\n');
    const r = run(src);
    assert.deepEqual(
      r.sites.map((s) => [s.line, s.symbol]),
      [
        [5, 'Svc.go'],
        [8, 'Svc.lam'],
        [13, 'outer.inner'],
        [16, '<module>'],
      ],
    );
  });

  test('dynamic id from env is unresolved with envVarName', () => {
    const src =
      'import os\n' +
      SDK +
      [
        'def a():',
        '    return client.workflows.invoke(os.environ["SWFTE_REPORT_WF"], {"w": 1})',
        'def b():',
        '    wf = os.getenv("SWFTE_OTHER_WF", "wf_default")',
        '    return client.workflows.invoke(wf, {"w": 1})',
        'def c(workflow_id):',
        '    return client.workflows.invoke(workflow_id, {"w": 1})',
        'def d():',
        '    return client.workflows.invoke(settings.report_workflow, {"w": 1})',
        '',
      ].join('\n');
    const r = run(src);
    assert.equal(r.sites.length, 4);
    for (const s of r.sites) {
      assert.equal(s.category, 'dynamic');
      assert.equal(s.artifact.unresolved, true);
      assert.equal(s.artifact.id, null, 'an unresolved id is never guessed');
      assert.equal(s.detector, 'py.dynamic');
    }
    assert.deepEqual(r.sites.map((s) => s.artifact.envVarName), ['SWFTE_REPORT_WF', 'SWFTE_OTHER_WF', undefined, undefined]);
  });

  test('a same-file constant folds into a resolved id', () => {
    const r = run(SDK + 'WF = "wf_Const"\n\ndef f():\n    client.workflows.invoke(WF, {"a": 1})\n');
    assert.equal(r.sites[0]!.artifact.id, 'wf_Const');
    assert.equal(r.sites[0]!.category, 'managed');
  });

  test('multiline call line is the first line of the call expression', () => {
    const src = SDK + ['def f():', '    return client.workflows.invoke(', '        "wf_ML",', '        {"a": 1},', '    )', ''].join('\n');
    const r = run(src);
    assert.equal(r.sites.length, 1);
    assert.equal(r.sites[0]!.line, 4);
  });
});

describe('py keys', () => {
  test('literal input keys are sorted; dict() keywords count; a variable bound to a literal counts', () => {
    const src =
      SDK +
      [
        'def f(a, b):',
        '    client.workflows.invoke("wf_K", {"zeta": a, "alpha": b})',
        '    payload = {"one": 1, "two": 2}',
        '    client.workflows.invoke("wf_K", payload)',
        '    client.workflows.invoke("wf_K", dict(k=1, j=2))',
        '    client.workflows.get_execution_history("wf_K")',
        '',
      ].join('\n');
    const r = run(src);
    assert.deepEqual(r.sites.map((s) => s.inputKeys), [['alpha', 'zeta'], ['one', 'two'], ['j', 'k'], []]);
  });

  test('kwargs input gives wildcard', () => {
    const src =
      SDK +
      [
        'def f(body, **kwargs):',
        '    client.workflows.invoke("wf_S", {**body, "a": 1})',
        '    client.workflows.invoke("wf_S", body)',
        '    client.workflows.invoke("wf_S", dict(**kwargs))',
        '',
      ].join('\n');
    const r = run(src);
    assert.deepEqual(r.sites.map((s) => s.inputKeys), [['*'], ['*'], ['*']]);
  });

  test('output cut at index, destructuring-free reads, envelope fields excluded', () => {
    const src =
      SDK +
      [
        'def f():',
        '    res = client.workflows.invoke_and_wait("wf_O", {})',
        '    print(res.status, res.execution_id)',
        '    return res.output["articles"][0]["title"], res.output.get("meta")',
        '',
      ].join('\n');
    const r = run(src);
    assert.deepEqual(r.sites[0]!.outputKeys, ['articles', 'meta']);
  });

  test('a field read and stored in a variable still counts as an output key', () => {
    const src = SDK + ['def f():', '    res = client.workflows.invoke_and_wait("wf_V", {})', '    title = res.output["title"]', '    out = res.output', '    n = out.get("count")', ''].join('\n');
    assert.deepEqual(run(src).sites[0]!.outputKeys, ['count', 'title']);
  });

  test('output passed whole', () => {
    const src = SDK + ['def f(sink):', '    res = client.workflows.invoke_and_wait("wf_W", {})', '    sink(res.output)', '    return res', ''].join('\n');
    const r = run(src);
    assert.deepEqual(r.sites[0]!.outputKeys, ['*']);
  });

  test('a result never read has no output keys', () => {
    const r = run(SDK + 'def f():\n    client.workflows.invoke("wf_N", {"a": 1})\n');
    assert.deepEqual(r.sites[0]!.outputKeys, []);
  });
});

describe('py raw HTTP', () => {
  test('literal URL, constant-folded URL and an f-string with a constant host', () => {
    const src = [
      'import requests',
      'import httpx',
      'import urllib.request',
      'BASE = "https://api.swfte.com/agents"',
      '',
      'def a(x):',
      '    return requests.post("https://api.swfte.com/agents/v2/workflows/wf_R1/invoke", json={"x": x})',
      'def b():',
      '    return httpx.get(BASE + "/v2/workflows/wf_R2/executions")',
      'def c(uid):',
      '    return requests.post(f"{BASE}/v1/agents/ag_R3/chat/{uid}", json={"message": "hi"})',
      'def d():',
      '    return urllib.request.urlopen(urllib.request.Request("https://api.swfte.com/agents/v1/public/agents/ag_R4/chat"))',
      '',
    ].join('\n');
    const r = run(src, 'app/raw.py');
    assert.deepEqual(
      r.sites.map((s) => [s.line, s.category, s.sdk, s.managed, s.op, s.artifact.kind, s.artifact.id, s.inputKeys]),
      [
        [7, 'raw-http', 'http', 'raw-http', 'run', 'workflow', 'wf_R1', ['x']],
        [9, 'raw-http', 'http', 'raw-http', 'read-output', 'workflow', 'wf_R2', []],
        [11, 'raw-http', 'http', 'raw-http', 'chat', 'agent', 'ag_R3', ['message']],
        [13, 'raw-http', 'http', 'raw-http', 'chat', 'agent', 'ag_R4', []],
      ],
    );
    assert.ok(r.sites.every((s) => s.detector === 'py.raw-http'));
  });

  test('an id built from a variable or env is unresolved; a foreign host is not a site; an httpx client base_url is followed', () => {
    const src = [
      'import os, requests, httpx',
      '',
      'def a(wf):',
      '    return requests.post(f"https://api.swfte.com/agents/v2/workflows/{wf}/invoke", json={})',
      'def b():',
      '    return requests.post(f"https://api.swfte.com/agents/v2/workflows/{os.environ[\'SWFTE_DUN_WF\']}/invoke", json={})',
      'def c():',
      '    return requests.post("https://example.com/v2/workflows/wf_X/invoke", json={})',
      'def d():',
      '    with httpx.Client(base_url="https://api.swfte.com/agents") as http:',
      '        return http.post("/v2/workflows/wf_Base/invoke", json={"q": 1})',
      '',
    ].join('\n');
    const r = run(src, 'app/raw2.py');
    assert.deepEqual(
      r.sites.map((s) => [s.line, s.category, s.artifact.id, s.artifact.envVarName ?? null]),
      [
        [4, 'dynamic', null, null],
        [6, 'dynamic', null, 'SWFTE_DUN_WF'],
        [11, 'raw-http', 'wf_Base', null],
      ],
    );
  });

  test('a dict or cache lookup keyed by a Swfte URL is not a request', () => {
    const src = [
      'import requests',
      '',
      'CACHE = {}',
      'def f():',
      '    return CACHE.get("https://api.swfte.com/agents/v2/workflows/wf_Cache/invoke")',
      'def g(registry):',
      '    return registry.post("https://api.swfte.com/agents/v2/workflows/wf_Reg/invoke")',
      'def h():',
      '    return requests.post("https://api.swfte.com/agents/v2/workflows/wf_Real/invoke", json={})',
      '',
    ].join('\n');
    assert.deepEqual(run(src, 'app/cache.py').sites.map((x) => x.artifact.id), ['wf_Real']);
  });

  test('a versioned invoke route records the pinned version', () => {
    const r = run('import requests\n\ndef f():\n    requests.post("https://api.swfte.com/agents/v2/workflows/wf_V/versions/4/invoke", json={"a": 1})\n');
    assert.equal(r.sites[0]!.artifact.pinnedVersion, '4');
  });
});

describe('py widget templates', () => {
  test('iframe and bootstrap script in string templates are widget embeds at the element line', () => {
    const src = [
      'IFRAME = """',
      '<div>',
      '  <iframe src="https://app.swfte.com/chat/ag_W1" width="400"></iframe>',
      '</div>',
      '"""',
      '',
      'def page(theme):',
      '    return f"""<script>',
      '      new SwfteChatWidget({{ agentId: "ag_W2", theme: "{theme}" }}).mount();',
      '    </script>"""',
      '',
    ].join('\n');
    const r = run(src, 'app/embeds.py');
    assert.deepEqual(
      r.sites.map((s) => [s.line, s.symbol, s.category, s.sdk, s.op, s.artifact.id]),
      [
        [3, '<module>', 'widget', 'widget-embed', 'embed', 'ag_W1'],
        [9, 'page', 'widget', 'widget-embed', 'embed', 'ag_W2'],
      ],
    );
  });

  test('a widget agent id from an f-string hole is dynamic', () => {
    const r = run('def f(agent):\n    return f\'<iframe src="https://app.swfte.com/chat/{agent}"></iframe>\'\n', 'app/e.py');
    assert.equal(r.sites.length, 1);
    assert.equal(r.sites[0]!.category, 'dynamic');
    assert.equal(r.sites[0]!.artifact.id, null);
    assert.equal(r.sites[0]!.artifact.unresolved, true);
  });
});

describe('py decoys, broken files and degradation', () => {
  test('decoys produce no sites', async () => {
    const src =
      SDK +
      [
        '# client.workflows.invoke("wf_C", {"a": 1})',
        'def f():',
        '    """Example: client.workflows.invoke("wf_D", {"a": 1})"""',
        '    s = \'client.workflows.invoke("wf_E", {"a": 1})\'',
        '    return s',
        '',
      ].join('\n');
    assert.deepEqual(run(src).sites, []);
    assert.deepEqual(run('import requests\n# requests.post("https://api.swfte.com/agents/v2/workflows/wf_H/invoke")\n').sites, []);

    // the corpus: only decoys (tests dirs, vendored, generated, forks, docs)
    const out = await detectProject(join(CORPUS, 'decoys'), { detectors: [...PY, ...JAVA], envFiles: ENV_FILES });
    assert.deepEqual(out.sites, []);
  });

  test('test files and mocked SDKs are not call sites', () => {
    const mocked = 'from unittest import mock\nfrom swfte import SwfteClient\n\ndef t():\n    c = mock.Mock(spec=SwfteClient)\n    c.workflows.invoke("wf_T", {"a": 1})\n';
    assert.deepEqual(run(mocked).sites, []);
    assert.deepEqual(run(SDK + 'client.workflows.invoke("wf_T", {})\n', 'tests/test_x.py').sites, []);
    assert.deepEqual(run(SDK + 'client.workflows.invoke("wf_T", {})\n', 'app/.venv/lib/x.py').sites, []);
  });

  test('invalid syntax does not throw and gives no sites from the broken region', () => {
    const src = SDK + ['def ok():', '    client.workflows.invoke("wf_OK", {"a": 1})', '', 'def broken(:', '    client.workflows.invoke("wf_BAD", {', ''].join('\n');
    const r = run(src);
    assert.ok(!r.sites.some((s) => s.artifact.id === 'wf_BAD'), 'the broken call is not reported');
    assert.deepEqual(r.sites.map((s) => s.artifact.id), ['wf_OK'], 'only the healthy call survives');
    assert.doesNotThrow(() => run('def (((\n  ]]]\n\x00\x01'));
  });

  test('missing grammar degrades to no sites', async () => {
    const src = SDK + 'def f():\n    client.workflows.invoke("wf_G", {"a": 1})\n';
    assert.equal(run(src).sites.length, 1);
    try {
      assert.equal(await initPythonParser('/nonexistent/tree-sitter-python.wasm'), false);
      assert.doesNotThrow(() => run(src));
      assert.deepEqual(run(src).sites, []);
    } finally {
      assert.equal(await initPythonParser(), true);
    }
    assert.equal(run(src).sites.length, 1);
  });

  test('env names are collected, never values', () => {
    const src = [
      'import os',
      'KEY = os.environ.get("SWFTE_API_KEY", "cm-canary-default-0000")',
      'BASE = os.getenv("SWFTE_BASE_URL")',
      'OTHER = os.environ["HOME"]',
      'from swfte import SwfteClient',
      'client = SwfteClient(api_key=KEY)',
      'client.workflows.invoke("wf_E", {})',
      '',
    ].join('\n');
    const r = run(src);
    assert.deepEqual([...new Set(r.envVarNames)].sort(), ['SWFTE_API_KEY', 'SWFTE_BASE_URL']);
    assert.ok(!JSON.stringify(r).includes('cm-canary-default-0000'), 'no value leaves the detector');
  });
});

describe('py corpus', () => {
  type KeySite = { path: string; line: number; language: string; category: string; symbol: string; sdk: string; op: string; managed: string; artifact: { kind: string; id: string | null; unresolved: boolean; envVarName?: string | null; alias?: string | null; pinnedVersion?: string | null }; inputKeys: string[]; outputKeys: string[] };

  async function compare(fixture: string, under = '') {
    const root = join(CORPUS, fixture);
    const key = JSON.parse(fs.readFileSync(join(root, 'answer-key.json'), 'utf8')) as { sites: KeySite[]; implementations: { path: string; line: number }[] };
    const out = await detectProject(root, { detectors: PY, envFiles: ENV_FILES });
    const want = key.sites.filter((s) => s.path.endsWith('.py') && s.path.startsWith(under));
    const got = out.sites.filter((s) => s.relPath.endsWith('.py'));
    assert.ok(want.length > 0, 'the fixture has Python sites');
    const fmt = (s: { path: string; line: number; artifact: KeySite['artifact']; inputKeys: string[]; outputKeys: string[] }) =>
      JSON.stringify([s.path, s.line, s.artifact.kind, s.artifact.id, s.artifact.unresolved, s.artifact.envVarName ?? null, s.artifact.alias ?? null, s.artifact.pinnedVersion ?? null, s.inputKeys, s.outputKeys]);
    assert.deepEqual(
      got.map((s) => fmt({ ...s, path: s.relPath })),
      want.map((s) => fmt(s)),
    );
    // category, symbol and transport agree too
    const by = new Map(got.map((s) => [`${s.relPath}:${s.line}`, s]));
    for (const w of want) {
      const g = by.get(`${w.path}:${w.line}`)!;
      assert.deepEqual([g.category, g.symbol, g.sdk, g.op, g.managed], [w.category, w.symbol, w.sdk, w.op, w.managed], `${w.path}:${w.line}`);
    }
    const implWant = key.implementations.filter((i) => i.path.endsWith('.py')).map((i) => `${i.path}:${i.line}`);
    assert.deepEqual(out.implementations.filter((i) => i.relPath.endsWith('.py')).map((i) => `${i.relPath}:${i.line}`), implWant);
  }

  test('py-fastapi: every answer-key site is found with the same path, line, artifact and keys', async () => {
    await compare('py-fastapi');
  });

  test('monorepo: the Python worker package resolves to its own lock', async () => {
    await compare('monorepo', 'py/');
  });
});

describe('Python scope binding index', () => {
  test('large scopes resolve every distinct call-site variable without crossing parse trees', () => {
    const source = SDK + Array.from({ length: 600 }, (_, i) =>
      `artifact_${i} = "wf_${i}"\nclient.workflows.invoke_and_wait(artifact_${i}, {"topic": "local"})`,
    ).join('\n');
    const r = run(source);
    assert.equal(r.sites.length, 600);
    assert.deepEqual(r.sites.map(site => site.artifact.id), Array.from({ length: 600 }, (_, i) => `wf_${i}`));
    const other = run(SDK + 'artifact_0 = "wf_other"\nclient.workflows.invoke_and_wait(artifact_0, {})\n');
    assert.equal(other.sites[0]!.artifact.id, 'wf_other');
  });
  test('scope shadowing, opaque loops and reassignment remain unresolved', () => {
    const r = run(SDK + [
      'artifact = "wf_outer"',
      'def local():',
      '    artifact = "wf_inner"',
      '    client.workflows.invoke_and_wait(artifact, {})',
      'client.workflows.invoke_and_wait(artifact, {})',
      'for artifact in items:',
      '    client.workflows.invoke_and_wait(artifact, {})',
    ].join('\n'));
    assert.equal(r.sites.length, 3);
    assert.equal(r.sites[0]!.artifact.id, 'wf_inner');
    assert.equal(r.sites[1]!.artifact.unresolved, true);
    assert.equal(r.sites[2]!.artifact.unresolved, true);
  });
});
