/**
 * Detector dispatch (docs/codemap/CONTRACT.md §7): detectProject runs detectors over the walked files
 * with their DetectContext and returns a deterministic DetectOutcome. The real detectors belong to
 * other work packages, so these tests use small fakes that report what they were given.
 */
import { test, describe, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { detectProject } from '../src/codemap/detect.js';
import { DETECTORS } from '../src/codemap/detectors/index.js';
import { assignIds } from '../src/codemap/fingerprint.js';
import { DEFAULT_ENV_FILES } from '../src/codemap/walk.js';
import type { DetectContext, DetectedSite, Detector, SourceFile } from '../src/codemap/types.js';

const KEY = Buffer.alloc(32, 0x42);
const REPO = 'r_fedcba9876543210fedcba9876543210';
const ENV_FILES = { secret: [...DEFAULT_ENV_FILES.secret, 'dot-env', 'dot-env.*'], names: [...DEFAULT_ENV_FILES.names, 'dot-env.example'] };

function write(root: string, rel: string, text: string) {
  const abs = join(root, rel);
  fs.mkdirSync(dirname(abs), { recursive: true });
  fs.writeFileSync(abs, text);
}

/** Reports `swfte.run("kind:id")` calls, symbol = nearest preceding `function name`. */
function fakeDetector(id: string, languages: SourceFile['language'][], seen?: Array<{ file: string; ctx: DetectContext }>): Detector {
  return {
    id,
    languages,
    detect(file, ctx) {
      seen?.push({ file: file.relPath, ctx });
      const sites: DetectedSite[] = [];
      const envVarNames: string[] = [];
      let symbol = '<module>';
      file.text.split('\n').forEach((line, i) => {
        const fn = /^\s*(?:function|def)\s+([A-Za-z_]\w*)/.exec(line);
        if (fn) symbol = fn[1]!;
        if (/^\s*(\/\/|#)/.test(line)) return; // comments are not calls
        for (const m of line.matchAll(/swfte\.run\("([a-z]+):([A-Za-z0-9_]+)"\)/g)) {
          sites.push({
            relPath: file.relPath,
            line: i + 1,
            symbol,
            language: file.language,
            category: 'managed',
            sdk: 'node',
            op: 'run',
            managed: 'typed-client',
            artifact: { kind: m[1]!, id: m[2]!, unresolved: false, pinnedVersion: null, alias: null },
            contractHash: null,
            inputKeys: [],
            outputKeys: [],
            detector: id,
          });
        }
        for (const m of line.matchAll(/env\.([A-Za-z_][A-Za-z0-9_]*)/g)) envVarNames.push(m[1]!);
      });
      return { sites, implementations: sites.length ? [{ relPath: file.relPath, line: 1, alias: 'impl' }] : [], envVarNames };
    },
  };
}

let root: string;

before(() => {
  root = fs.realpathSync(fs.mkdtempSync(join(tmpdir(), 'cmap-detect-')));
  write(root, 'package.json', JSON.stringify({ name: 'shop' }));
  write(root, 'swfte.json', JSON.stringify({ version: 1, baseUrl: 'https://api.swfte.com/agents', workspaceId: null, artifacts: [
    { catalogRef: 'workflow:wf_order', alias: 'order', language: 'typescript', framework: 'plain-ts', outDir: 'swfte', contractHash: 'abc1234', pinnedVersion: '2', files: ['swfte/order.ts'] },
  ] }));
  write(root, 'src/b.ts', 'function pay() {\n  swfte.run("workflow:wf_pay");\n  const k = env.SWFTE_PAY_ID;\n}\n');
  write(root, 'src/a.ts', 'function checkout() {\n  swfte.run("workflow:wf_order"); swfte.run("agent:ag_help");\n  // swfte.run("workflow:wf_commented")\n  swfte.run("workflow:wf_order");\n}\nconst lower = env.not_a_name;\n');
  write(root, 'svc/app.py', 'def handler():\n    swfte.run("agent:ag_py")\n');
  write(root, 'web/page.html', '<script>swfte.run("widget:wd_1")</script>\n');
  write(root, 'node_modules/dep/index.js', 'function vendored() { swfte.run("workflow:wf_vendored") }\n');
  write(root, 'gen/api.ts', '// @generated by openapi\nfunction gen() { swfte.run("workflow:wf_gen") }\n');
  // Neutral stand-in for .env.example (CONTRACT D10): no file named .env* is ever created.
  write(root, 'dot-env.example', 'SWFTE_EXAMPLE_ID=\n');
});

after(() => fs.rmSync(root, { recursive: true, force: true }));

const ts = () => fakeDetector('ts.fake', ['typescript', 'javascript']);

describe('dispatch', () => {
  test('each detector sees only files of its languages, with the nearest lock as context', async () => {
    const seenTs: Array<{ file: string; ctx: DetectContext }> = [];
    const seenPy: Array<{ file: string; ctx: DetectContext }> = [];
    const out = await detectProject(root, { detectors: [fakeDetector('ts.fake', ['typescript'], seenTs), fakeDetector('py.fake', ['python'], seenPy)] });
    assert.deepEqual(seenTs.map((s) => s.file), ['src/a.ts', 'src/b.ts']);
    assert.deepEqual(seenPy.map((s) => s.file), ['svc/app.py']);
    assert.equal(seenTs[0]!.ctx.lockDir, '');
    assert.deepEqual(seenTs[0]!.ctx.locks.map((l) => [l.alias, l.pinnedVersion, l.files]), [['order', '2', ['swfte/order.ts']]]);
    assert.equal(out.filesScanned, 4, 'a.ts, b.ts, app.py, page.html (vendored and generated skipped)');
  });

  test('the default detector set is the registry (empty today): files are scanned, nothing is invented', async () => {
    assert.equal(DETECTORS.length >= 0, true);
    const out = await detectProject(root, { envFiles: ENV_FILES });
    assert.equal(out.filesScanned, 4);
    if (DETECTORS.length === 0) assert.deepEqual(out.sites, []);
    assert.deepEqual(out.envVarNames, ['SWFTE_EXAMPLE_ID']);
  });

  test('outcome: sites in (file, line) order with detector order breaking ties; implementations deduplicated', async () => {
    const out = await detectProject(root, { detectors: [ts(), fakeDetector('html.fake', ['html']), fakeDetector('ts.second', ['typescript'])] });
    assert.deepEqual(
      out.sites.map((s) => `${s.relPath}:${s.line}:${s.artifact.id}:${s.detector}`),
      [
        'src/a.ts:2:wf_order:ts.fake',
        'src/a.ts:2:ag_help:ts.fake',
        'src/a.ts:2:wf_order:ts.second',
        'src/a.ts:2:ag_help:ts.second',
        'src/a.ts:4:wf_order:ts.fake',
        'src/a.ts:4:wf_order:ts.second',
        'src/b.ts:2:wf_pay:ts.fake',
        'src/b.ts:2:wf_pay:ts.second',
        'web/page.html:1:wd_1:html.fake',
      ]
    );
    assert.deepEqual(out.implementations, [
      { relPath: 'src/a.ts', line: 1, alias: 'impl' },
      { relPath: 'src/b.ts', line: 1, alias: 'impl' },
      { relPath: 'web/page.html', line: 1, alias: 'impl' },
    ]);
    const again = await detectProject(root, { detectors: [ts(), fakeDetector('html.fake', ['html']), fakeDetector('ts.second', ['typescript'])] });
    assert.deepEqual(again, out);
  });

  test('env var names: detector names that are valid, plus the names env file, sorted and unique', async () => {
    const out = await detectProject(root, { detectors: [ts()], envFiles: ENV_FILES });
    assert.deepEqual(out.envVarNames, ['SWFTE_EXAMPLE_ID', 'SWFTE_PAY_ID']);
  });

  test('envFiles is threaded to the walk: without the override the stand-in names file is not an env file', async () => {
    const out = await detectProject(root, { detectors: [ts()] });
    assert.deepEqual(out.envVarNames, ['SWFTE_PAY_ID']);
  });

  test('packages holds every scanned file with its pkgId and package-relative path', async () => {
    const out = await detectProject(root, { detectors: [ts()] });
    assert.deepEqual([...out.packages.keys()], ['src/a.ts', 'src/b.ts', 'svc/app.py', 'web/page.html']);
    assert.deepEqual(out.packages.get('svc/app.py'), { pkgId: 'shop', pkgRelPath: 'svc/app.py' });
  });

  test('a detector cannot attribute a site to another file', async () => {
    const liar: Detector = {
      id: 'ts.liar',
      languages: ['typescript'],
      detect: (file) => ({ sites: ts().detect(file, { locks: [], lockDir: null }).sites.map((s) => ({ ...s, relPath: 'somewhere/else.ts' })), implementations: [], envVarNames: [] }),
    };
    const out = await detectProject(root, { detectors: [liar] });
    assert.ok(out.sites.length > 0);
    for (const s of out.sites) assert.ok(out.packages.has(s.relPath), s.relPath);
  });

  test('a detector that throws marks the outcome truncated and the others still run', async () => {
    const broken: Detector = { id: 'ts.broken', languages: ['typescript'], detect: () => { throw new Error('parse failure'); } };
    const out = await detectProject(root, { detectors: [broken, fakeDetector('py.fake', ['python'])] });
    assert.equal(out.truncated, true);
    assert.deepEqual(out.sites.map((s) => s.artifact.id), ['ag_py']);
    const clean = await detectProject(root, { detectors: [fakeDetector('py.fake', ['python'])] });
    assert.equal(clean.truncated, false);
  });
});

describe('options the evaluation mutants use', () => {
  test('skipDirs: [] reaches vendored code; the default does not', async () => {
    const ids = async (o = {}) => (await detectProject(root, { detectors: [ts()], ...o })).sites.map((s) => s.artifact.id);
    assert.ok(!(await ids()).includes('wf_vendored'));
    assert.ok((await ids({ skipDirs: [] })).includes('wf_vendored'));
  });

  test('skipGenerated: false reaches files another tool generated; the default does not', async () => {
    const ids = async (o = {}) => (await detectProject(root, { detectors: [ts()], ...o })).sites.map((s) => s.artifact.id);
    assert.ok(!(await ids()).includes('wf_gen'));
    assert.ok((await ids({ skipGenerated: false })).includes('wf_gen'));
  });

  test('preprocess rewrites the text the detectors see (comments turned into code), never the file identity', async () => {
    const out = await detectProject(root, {
      detectors: [ts()],
      preprocess: (f) => ({ relPath: 'hijack.ts', language: 'python', text: f.text.replace(/^(\s*)\/\/\s*/gm, '$1') }),
    });
    assert.ok(out.sites.some((s) => s.artifact.id === 'wf_commented'));
    assert.ok(out.sites.every((s) => s.relPath.startsWith('src/') || s.relPath.startsWith('web/')));
  });

  test('maxFiles and maxFileBytes pass through to the walk and set truncated', async () => {
    assert.equal((await detectProject(root, { detectors: [ts()], maxFiles: 1 })).truncated, true);
    const tiny = await detectProject(root, { detectors: [ts()], maxFileBytes: 60 });
    assert.equal(tiny.truncated, true);
    assert.ok(!tiny.packages.has('src/a.ts'));
  });
});

describe('end to end with fingerprints', () => {
  test('inserting lines and comments above and between calls leaves every id unchanged', async () => {
    const r = fs.realpathSync(fs.mkdtempSync(join(tmpdir(), 'cmap-stable-')));
    try {
      const body = 'function checkout() {\n  swfte.run("workflow:wf_order");\n  swfte.run("workflow:wf_order");\n}\nfunction other() {\n  swfte.run("agent:ag_1");\n}\n';
      write(r, 'src/a.ts', body);
      const first = await detectProject(r, { detectors: [ts()] });
      const ids1 = assignIds(first.sites, first.packages, KEY, REPO).map((s) => s.id);
      write(r, 'src/a.ts', `// header\n\nimport x from "y";\n\n${body.replace('  swfte.run("workflow:wf_order");\n  swfte', '  swfte.run("workflow:wf_order");\n  // a note\n\n  const n = 1;\n  swfte').replace('function other() {\n', 'function other() {\n  const unrelated = 2;\n')}`);
      const second = await detectProject(r, { detectors: [ts()] });
      assert.notDeepEqual(second.sites.map((s) => s.line), first.sites.map((s) => s.line), 'the lines did move');
      assert.deepEqual(assignIds(second.sites, second.packages, KEY, REPO).map((s) => s.id), ids1);
    } finally {
      fs.rmSync(r, { recursive: true, force: true });
    }
  });
});
