import {test} from 'node:test';import assert from 'node:assert/strict';
import {widgetTools} from '../src/tools/widgets.js';import {allTools} from '../src/tools/index.js';import {TOOL_GROUPS} from '../src/config.js';
const tool=(n:string)=>widgetTools.find(t=>t.name===n)!;
function context(replies:any[],allowDeploy=true){const calls:any[]=[];return {calls,config:{allowDeploy},client:{request:async(r:any)=>{calls.push(r);if(!replies.length)throw Error('Unexpected request');return replies.shift();}}}as any;}
test('configuration encodes IDs, avoids write retries and verifies persistence',async()=>{const c=context([{id:'w/x?',workspaceId:'1'}, {}, {id:'w/x?',workspaceId:'1',viewType:'FORM'}]);const r:any=await tool('swfte_widgets_configure').execute({widgetId:'w/x?',configuration:{viewType:'FORM'}},c);assert(r.persisted);assert.equal(c.calls[0].path,'/api/v2/widgets/w%2Fx%3F');assert.equal(c.calls[1].retries,0);assert(!c.calls.some((r:any)=>r.headers));await assert.rejects(()=>tool('swfte_widgets_configure').execute({widgetId:'w',configuration:{viewType:'FORM'}},context([{id:'w',workspaceId:'1'},{},{id:'w',workspaceId:'1'}])),/READBACK_MISMATCH/);});
test('unsupported fields and workspace overrides reject',()=>{for(const configuration of [{unknown:true},{active:true},{stateScope:'WORKSPACE'},{}])assert.throws(()=>tool('swfte_widgets_configure').inputSchema.parse({widgetId:'w',configuration}));assert.throws(()=>tool('swfte_widgets_configure').inputSchema.parse({widgetId:'w',workspaceId:'other',configuration:{viewType:'TABLE'}}));});
test('binding create verifies native readback and no source execution',async()=>{const body={sourceType:'STUDIO_OPERATIONS',sourceRef:'S01',paramsJson:JSON.stringify({access:'WORKSPACE',schemaVersion:1})};const c=context([{id:'b/x',workspaceId:'1'},{id:'b/x',workspaceId:'1',...body}]);const r:any=await tool('swfte_widget_bindings_create').execute({sourceType:'STUDIO_OPERATIONS',sourceRef:'S01'},c);assert.equal(c.calls[0].path,'/v1/widget-bindings');assert.equal(c.calls[0].retries,0);assert.equal(c.calls[1].path,'/v1/widget-bindings/b%2Fx');assert.equal(r.sourceExecutionVerified,false);assert.equal(r.binding.paramsJson,undefined);await assert.rejects(()=>tool('swfte_widget_bindings_create').execute({sourceType:'STUDIO_OPERATIONS',sourceRef:'S01'},context([{id:'b'},{id:'b'}])),/READBACK_MISMATCH/);});
test('binding schema rejects unsupported sources, credential URLs and unreviewed public snapshots',()=>{for(const input of [{sourceType:'MODULE',sourceRef:'x'},{sourceType:'HTTP',sourceRef:'https://example.com',projection:'x'},{sourceType:'HTTP',sourceRef:'https://user:secret@example.com',publicDataConfirmed:true,projection:'x'},{sourceType:'STUDIO_OPERATIONS',sourceRef:'OTHER'},{sourceType:'STUDIO_OPERATIONS',sourceRef:'S01',paramsJson:'secret'}])assert.throws(()=>tool('swfte_widget_bindings_create').inputSchema.parse(input));});
test('binding reads project metadata and encode IDs',async()=>{const c=context([{id:'b/?',workspaceId:'1',query:'private',paramsJson:'secret',sourceRef:'https://x?secret'},[{id:'b',workspaceId:'1',paramsJson:'secret'}]]);assert.deepEqual(await tool('swfte_widget_bindings_get').execute({bindingId:'b/?'},c),{id:'b/?',workspaceId:'1'});assert.equal(c.calls[0].path,'/v1/widget-bindings/b%2F%3F');assert.deepEqual(await tool('swfte_widget_bindings_list').execute({},c),[{id:'b',workspaceId:'1'}]);});
test('lifecycle confirmation and deployment setting prevent all calls',async()=>{for(const action of ['pause','resume','rotate'])for(const [confirm,allow] of [[false,true],[true,false]]){const c=context([],allow);const r:any=await tool('swfte_widgets_lifecycle').execute({widgetId:'w',action,confirm},c);assert.equal(r.executed,false);assert.equal(c.calls.length,0);}});
test('pause and resume verify scoped current release while active stays true',async()=>{for(const action of ['pause','resume']){const saved={id:'w/x',workspaceId:'1',active:true,deploymentId:'d'};const c=context([saved,{},saved,[{id:'d',widgetId:'w/x',workspaceId:'1',status:action==='resume'?'LIVE':'PAUSED'}]]);const r:any=await tool('swfte_widgets_lifecycle').execute({widgetId:'w/x',action,confirm:true},c);assert(r.executed);assert.equal(r.runtimeVerified,false);assert.equal(c.calls[1].path,`/api/v2/widgets/w%2Fx/${action}`);assert.equal(c.calls[1].retries,0);}const saved={id:'w',workspaceId:'1',deploymentId:'d'};await assert.rejects(()=>tool('swfte_widgets_lifecycle').execute({widgetId:'w',action:'resume',confirm:true},context([saved,{},saved,[{id:'d',widgetId:'w',workspaceId:'other',status:'LIVE'}]])),/READBACK_MISMATCH/);});
test('rotation proves scoped key reference changed without exposing key material',async()=>{const before={id:'w',workspaceId:'1',deploymentId:'d',jwksKeyId:'old'};const c=context([before,{newKid:'new',privateKey:'secret'},{...before,jwksKeyId:'new',privateKey:'secret'}]);const r:any=await tool('swfte_widgets_lifecycle').execute({widgetId:'w',action:'rotate',confirm:true},c);assert.equal(c.calls[1].path,'/api/v2/widgets/w/jwks/rotate');assert.equal(r.widget.privateKey,undefined);await assert.rejects(()=>tool('swfte_widgets_lifecycle').execute({widgetId:'w',action:'rotate',confirm:true},context([before,{newKid:'new'},before])),/READBACK_MISMATCH/);});
test('configured API-key workspace and binding IDs must match readback',async()=>{const c=context([{id:'b',workspaceId:'other'}]);c.client.credentialKind='api-key';c.client.configuredWorkspaceId='1';await assert.rejects(()=>tool('swfte_widget_bindings_get').execute({bindingId:'b'},c),/workspace mismatch/);await assert.rejects(()=>tool('swfte_widget_bindings_get').execute({bindingId:'b'},context([{id:'wrong',workspaceId:'1'}])),/identity mismatch/);});
test('actual advertisement includes exactly five optional widget-group tools',()=>{assert(TOOL_GROUPS.includes('widgets'));assert.equal(widgetTools.length,5);for(const t of widgetTools){const r=allTools.filter(x=>x.name===t.name);assert.equal(r.length,1);assert.equal(r[0].group,'widgets');}});

test('native projection rejects silent pass-through shapes and accepts supported key selection',()=>{const t=tool('swfte_widget_bindings_create');for(const projection of ['rows','{}','[]','{"columns":["safe"]}','{"key":""}'])assert.throws(()=>t.inputSchema.parse({sourceType:'HTTP',sourceRef:'https://example.com/public',publicDataConfirmed:true,projection}));assert(t.inputSchema.parse({sourceType:'HTTP',sourceRef:'https://example.com/public',publicDataConfirmed:true,projection:'{"key":"publicRows"}'}));});

test('binding metadata reveals only allowlisted Studio renderer source references',async()=>{const rows=[{id:'a',workspaceId:'1',sourceType:'STUDIO_OPERATIONS',sourceRef:'S01'},{id:'b',workspaceId:'1',sourceType:'STUDIO_OPERATIONS',sourceRef:'secret'},{id:'c',workspaceId:'1',sourceType:'HTTP',sourceRef:'https://host?secret'}];const result:any=await tool('swfte_widget_bindings_list').execute({},context([rows]));assert.equal(result[0].sourceRef,'S01');assert.equal(result[1].sourceRef,undefined);assert.equal(result[2].sourceRef,undefined);});
