# Generated by @swfte/mcp-server (swfte add / swfte_scaffold_client). Do not edit by hand - run `swfte sync`.
# Source of truth: Swfte Studio catalog entry workflow:wf_Inv3Xt
# Artifact: Invoice extract
# Extracts vendor, total and line items from an invoice PDF.
# Contract hash: a21ddf9a08a3493cfbe18878a04fa37c47775c63f1b0bb2df0e4d3c93e5d1164 (recorded in swfte.json; a different hash means the contract moved).
#
# Server-side only: reads SWFTE_API_KEY from the environment.
# Configure via .env: SWFTE_API_KEY, SWFTE_BASE_URL, SWFTE_WORKSPACE_ID. Standard library only (Python 3.8+).
from __future__ import annotations

import json
import os
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Dict, List, Literal, Optional, TypedDict, Union

CATALOG_REF = "workflow:wf_Inv3Xt"
CONTRACT_HASH = "a21ddf9a08a3493cfbe18878a04fa37c47775c63f1b0bb2df0e4d3c93e5d1164"
# Published version this client runs (None: unpinned, runs the latest published version).
PINNED_VERSION: Optional[str] = None
# Identifies this generated client to Swfte (counts adopter runs; never carries payloads).
SWFTE_CLIENT = "python/0.2.0; ref=workflow:wf_Inv3Xt; hash=a21ddf9a08a3493cfbe18878a04fa37c47775c63f1b0bb2df0e4d3c93e5d1164"
# swfte-shape: {"in":{"currency":"string","fileUrl":"string!"},"out":{"lines":"array","total":"number","vendor":"string"}}

INVOKE_METHOD = "POST"
INVOKE_PATH = "/v2/workflows/wf_Inv3Xt/invoke"
INVOKE_AUTH = "api_key"
INVOKE_ASYNC = True
STATUS_PATH = "/v2/workflows/executions/{executionId}/status"
DEFAULT_BASE_URL = "https://api.swfte.com/agents"

TERMINAL = {"COMPLETED", "SUCCEEDED", "SUCCESS", "FAILED", "FAILURE", "ERROR", "CANCELLED", "CANCELED", "TIMEOUT", "TIMED_OUT", "TERMINATED", "REJECTED"}
WAITING = {"PAUSED", "WAITING_FOR_INPUT", "AWAITING_HUMAN"}
SUCCESS = {"COMPLETED", "SUCCEEDED", "SUCCESS"}


_InvoiceExtractInputRequired = TypedDict("_InvoiceExtractInputRequired", {
    "fileUrl": str,
})
_InvoiceExtractInputOptional = TypedDict("_InvoiceExtractInputOptional", {
    "currency": str,
}, total=False)


class InvoiceExtractInput(_InvoiceExtractInputRequired, _InvoiceExtractInputOptional):
    pass


InvoiceExtractOutput = TypedDict("InvoiceExtractOutput", {
    "total": float,
    "vendor": str,
    "lines": List[Dict[str, Any]],
}, total=False)


class InvokeResult(TypedDict):
    ok: bool
    status: str
    execution_id: Optional[str]
    output: Any
    reply: Optional[str]
    raw: Any


class SwfteRequestError(Exception):
    def __init__(self, status: int, body: str, path: str) -> None:
        super().__init__(f"Swfte request failed: {status} on {path}: {body[:300]}")
        self.status = status
        self.body = body
        self.path = path


def _fill(path: str, values: Dict[str, str]) -> str:
    def repl(m: "re.Match[str]") -> str:
        key = m.group(1)
        if not values.get(key):
            raise ValueError(f"Missing value for path placeholder {{{key}}}")
        return urllib.parse.quote(str(values[key]), safe="")

    return re.sub(r"\{([A-Za-z_][A-Za-z0-9_]*)\}", repl, path)


def _call(method: str, path: str, body: Any, api_key: Optional[str], base_url: Optional[str], workspace_id: Optional[str], timeout_s: float) -> Any:
    base = (base_url or os.environ.get("SWFTE_BASE_URL") or DEFAULT_BASE_URL).rstrip("/")
    headers = {"Accept": "application/json", "X-Swfte-Client": SWFTE_CLIENT}
    if INVOKE_AUTH != "public":
        key = api_key or os.environ.get("SWFTE_API_KEY")
        if not key:
            raise RuntimeError("SWFTE_API_KEY is not set (see .env.example).")
        headers["Authorization"] = f"Bearer {key}"
        if not key.startswith("pat_"):
            headers["X-API-Key"] = key
            ws = workspace_id or os.environ.get("SWFTE_WORKSPACE_ID")
            if ws:
                headers["X-Workspace-ID"] = ws
    url = base + path
    data = None
    if body is not None:
        if method == "GET":
            query = urllib.parse.urlencode({k: v for k, v in dict(body).items() if v is not None})
            if query:
                url += ("&" if "?" in url else "?") + query
        else:
            headers["Content-Type"] = "application/json"
            data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=max(1.0, timeout_s)) as res:
            text = res.read().decode("utf-8")
    except urllib.error.HTTPError as err:
        raise SwfteRequestError(err.code, err.read().decode("utf-8", "replace"), path) from None
    if not text:
        return None
    try:
        return json.loads(text)
    except ValueError:
        return text


def _status(snapshot: Any) -> str:
    if isinstance(snapshot, dict):
        execution = snapshot.get("execution")
        if isinstance(execution, dict) and execution.get("status"):
            return str(execution["status"]).upper()
        return str(snapshot.get("status") or "UNKNOWN").upper()
    return "UNKNOWN"


def _output(snapshot: Any) -> Any:
    if not isinstance(snapshot, dict):
        return None
    execution = snapshot.get("execution")
    if isinstance(execution, dict) and execution.get("outputData") is not None:
        return execution["outputData"]
    for key in ("outputData", "output", "result"):
        if snapshot.get(key) is not None:
            return snapshot[key]
    return None


def invoke_invoice_extract(
    inputs: InvoiceExtractInput,
    *,
    api_key: Optional[str] = None,
    base_url: Optional[str] = None,
    workspace_id: Optional[str] = None,
    timeout_s: float = 300.0,
    poll_interval_s: float = 2.0,
) -> InvokeResult:
    """Extracts vendor, total and line items from an invoice PDF."""
    deadline = time.monotonic() + timeout_s
    path = _fill(INVOKE_PATH, {})
    started = _call(INVOKE_METHOD, path, inputs, api_key, base_url, workspace_id, timeout_s)
    if not INVOKE_ASYNC:
        reply = None
        if False and isinstance(started, dict):
            # content is canonical; response is the legacy alias.
            value = started.get("content") if started.get("content") is not None else started.get("response")
            reply = value if isinstance(value, str) else None
        return {"ok": True, "status": "COMPLETED", "execution_id": None, "output": started, "reply": reply, "raw": started}
    execution_id = ""
    if isinstance(started, dict):
        nested = started.get("execution") if isinstance(started.get("execution"), dict) else {}
        execution_id = str(started.get("executionId") or nested.get("id") or started.get("id") or "")
    if not execution_id or not STATUS_PATH:
        return {"ok": False, "status": "ACCEPTED", "execution_id": execution_id or None, "output": None, "reply": None, "raw": started}
    status_path = _fill(STATUS_PATH, {"executionId": execution_id, "id": execution_id})
    while True:
        remaining = deadline - time.monotonic()
        snapshot = _call("GET", status_path, None, api_key, base_url, workspace_id, remaining)
        status = _status(snapshot)
        if status in TERMINAL or status in WAITING:
            return {"ok": status in SUCCESS, "status": status, "execution_id": execution_id, "output": _output(snapshot), "reply": None, "raw": snapshot}
        if time.monotonic() + poll_interval_s > deadline:
            raise TimeoutError(f"Timed out waiting for execution {execution_id} (last status {status}); poll {status_path}.")
        time.sleep(poll_interval_s)
# swfte-checksum: 135ab316944d7286
