/**
 * Java parsing for the code map detectors (docs/codemap/CONTRACT.md §2.1, §7). One `web-tree-sitter`
 * parser over the vendored grammar, initialised once at import time (top-level await) because
 * `Detector.detect` is synchronous. Source text stays in this process and is never serialised.
 *
 * Everything here is structural: symbols, scope lookups, string templates. A value the code does not
 * spell out in a literal is reported as dynamic, never guessed.
 */
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Language, Parser, type Node, type Tree } from 'web-tree-sitter';
import { mergePieces, type Piece } from '../py/route.js';
import { initRuntime } from '../py/runtime.js';

export type JNode = Node;
export type { Piece };

const DEFAULT_WASM = fileURLToPath(new URL('../../grammars/tree-sitter-java.wasm', import.meta.url));
let parser: Parser | null = null;
/** Bumps every time the grammar is (re)loaded, so per-file caches never outlive their parser. */
export let grammarGeneration = 0;

/**
 * (Re)load the Java grammar. Returns false, leaving no parser, when the WASM cannot be read or loaded:
 * detectors then report nothing and the scan goes on (edge case E9).
 */
export async function initJavaParser(wasmPath: string = DEFAULT_WASM): Promise<boolean> {
  try {
    await initRuntime();
    const language = await Language.load(fs.readFileSync(wasmPath));
    const p = new Parser();
    p.setLanguage(language);
    parser = p;
    grammarGeneration++;
    return true;
  } catch {
    parser = null;
    grammarGeneration++;
    return false;
  }
}

await initJavaParser();

/** Parse and hand the tree to `fn`; the native tree is always freed. Null when no grammar is loaded. */
export function withTree<T>(text: string, fn: (root: JNode) => T): T | null {
  if (!parser) return null;
  let tree: Tree | null = null;
  try {
    tree = parser.parse(text);
    if (!tree) return null;
    return fn(tree.rootNode);
  } catch {
    return null;
  } finally {
    if (tree) {
      // Cached Nodes reference this Tree and its source callback. Their lifetime ends here.
      NAMED_CHILDREN_CACHE.delete(tree);
      SCOPE_INDEX.delete(tree);
      FIELD_INDEX.delete(tree);
      tree.delete();
    }
  }
}

// ---------------------------------------------------------------------------------------------
// Paths and files that never hold call sites (decoys): tests, vendored and generated trees.

const VENDORED_DIRS = new Set(['target', 'build', 'out', 'node_modules', '.git', '.gradle', '.idea', 'generated-sources']);

export function isIgnoredPath(relPath: string): boolean {
  const segs = relPath.split('/');
  const base = segs[segs.length - 1] ?? '';
  const dirs = segs.slice(0, -1);
  if (dirs.some((s) => VENDORED_DIRS.has(s))) return true;
  // Maven/Gradle test source roots, then the usual test class names.
  for (let i = 0; i + 1 < dirs.length; i++) if (dirs[i] === 'src' && /^(test|integrationTest|testFixtures|it)$/.test(dirs[i + 1]!)) return true;
  return /(?:Test|Tests|IT|TestCase)\.java$/.test(base) || /^Test[A-Z]\w*\.java$/.test(base);
}

/** Another tool's generated marker in the header, or a `@Generated` annotation on the file's class. */
export function isForeignGenerated(text: string): boolean {
  const head = text.slice(0, 4096).split(/\r?\n/).slice(0, 40).join('\n');
  if (/Generated by @swfte\//.test(head)) return false;
  if (/@generated\b/i.test(head) || /Code generated\b.*\bDO NOT EDIT\b/i.test(head)) return true;
  return /^\s*@(?:[A-Za-z_][\w.]*\.)?Generated\s*\(/m.test(text.slice(0, 8192));
}

/** A file that uses Mockito or Spring's mock beans is a test even when it sits in a main tree. */
export function usesMocks(root: JNode): boolean {
  return children(root).some((n) => n.type === 'import_declaration' && /\borg\.mockito\b|\borg\.springframework\.boot\.test\b|\borg\.junit\b/.test(n.text));
}

// ---------------------------------------------------------------------------------------------
// Tree helpers

/** A node in (or containing) a syntax error: edge case E8 says a broken region yields no sites. */
export function isBroken(n: JNode): boolean {
  if (n.hasError || n.isMissing) return true;
  for (let p = n.parent; p; p = p.parent) if (p.type === 'ERROR') return true;
  return false;
}

export const lineOf = (n: JNode): number => n.startPosition.row + 1;

const EMPTY_NAMED_CHILDREN: readonly JNode[] = Object.freeze([] as JNode[]);
const NAMED_CHILDREN_CACHE = new WeakMap<Tree, Map<number, readonly JNode[]>>();

/** Native getters create fresh wrappers; detector passes share immutable vectors inside one tree. */
function namedChildren(n: JNode): readonly JNode[] {
  let nodes = NAMED_CHILDREN_CACHE.get(n.tree);
  const cached = nodes?.get(n.id);
  if (cached) return cached;
  const count = n.namedChildCount;
  if (count === 0) return EMPTY_NAMED_CHILDREN;
  const out: JNode[] = [];
  for (let i = 0; i < count; i++) {
    const c = n.namedChild(i);
    if (c) out.push(c);
  }
  if (!nodes) { nodes = new Map(); NAMED_CHILDREN_CACHE.set(n.tree, nodes); }
  const vector = Object.freeze(out);
  nodes.set(n.id, vector);
  return vector;
}

export function children(n: JNode): JNode[] {
  return namedChildren(n).filter(child => child.type !== 'line_comment' && child.type !== 'block_comment');
}

/** Depth-first walk over named nodes; `visit` returning false prunes the subtree. */
export function walk(n: JNode, visit: (n: JNode) => boolean | void): void {
  if (visit(n) === false) return;
  for (const child of namedChildren(n)) walk(child, visit);
}

export const argsOf = (call: JNode): JNode[] => {
  const a = call.childForFieldName('arguments');
  return a ? children(a) : [];
};

/** The name of a method call (`invoke` in `client.workflows().invoke(...)`). */
export const nameOf = (call: JNode): string => call.childForFieldName('name')?.text ?? '';

const TYPE_DECLS = new Set(['class_declaration', 'interface_declaration', 'enum_declaration', 'record_declaration', 'annotation_type_declaration']);
const isTypeDecl = (n: JNode): boolean => TYPE_DECLS.has(n.type);

const isAnonymousBody = (classBody: JNode): boolean => classBody.parent?.type === 'object_creation_expression' || classBody.parent?.type === 'enum_constant';

function methodsNamed(typeDecl: JNode, name: string, ctor: boolean): number {
  const body = typeDecl.childForFieldName('body');
  if (!body) return 0;
  let n = 0;
  for (const c of children(body)) {
    if (c.type === (ctor ? 'constructor_declaration' : 'method_declaration') && c.childForFieldName('name')?.text === name) n++;
  }
  return n;
}

function arityOf(m: JNode): number {
  const params = m.childForFieldName('parameters');
  return params ? children(params).length : 0;
}

/**
 * `Class.method` (overloads `Class.method#<arity>`), `Class.<init>` (constructors, instance field
 * initialisers and instance blocks), `Class.<clinit>` (static fields and blocks). Lambdas and anonymous
 * class bodies contribute nothing (D2): the nearest NAMED enclosing symbol wins. A nested type is named by
 * its own simple name.
 */
export function symbolOf(n: JNode): string {
  for (let p: JNode | null = n.parent; p; p = p.parent) {
    const owner = (): JNode | null => {
      for (let t: JNode | null = p!.parent; t; t = t.parent) {
        if (t.type === 'class_body' && isAnonymousBody(t)) return null;
        if (isTypeDecl(t)) return t;
      }
      return null;
    };
    const cls = (t: JNode | null): string | null => t?.childForFieldName('name')?.text ?? null;
    switch (p.type) {
      case 'method_declaration': {
        if (p.parent?.type === 'class_body' && isAnonymousBody(p.parent)) continue;
        const t = owner();
        const c = cls(t);
        const name = p.childForFieldName('name')?.text;
        if (!name) continue;
        const overloaded = t ? methodsNamed(t, name, false) > 1 : false;
        const sym = `${c ? `${c}.` : ''}${name}${overloaded ? `#${arityOf(p)}` : ''}`;
        return sym;
      }
      case 'constructor_declaration': {
        const t = owner();
        const c = cls(t);
        if (!c) continue;
        const overloaded = methodsNamed(t!, c, true) > 1;
        return `${c}.<init>${overloaded ? `#${arityOf(p)}` : ''}`;
      }
      case 'compact_constructor_declaration': {
        const c = cls(owner());
        if (c) return `${c}.<init>`;
        continue;
      }
      case 'enum_constant': {
        const c = cls(owner());
        if (c) return `${c}.<clinit>`;
        continue;
      }
      case 'static_initializer': {
        const c = cls(owner());
        if (c) return `${c}.<clinit>`;
        continue;
      }
      case 'field_declaration': {
        if (p.parent?.type !== 'class_body' || isAnonymousBody(p.parent)) continue;
        const t = owner();
        const c = cls(t);
        if (!c) continue;
        const isStatic = t?.type === 'interface_declaration' || /\bstatic\b/.test(p.children.find((x) => x?.type === 'modifiers')?.text ?? '');
        return `${c}.${isStatic ? '<clinit>' : '<init>'}`;
      }
      case 'block': {
        if (p.parent?.type !== 'class_body' || isAnonymousBody(p.parent)) continue;
        const c = cls(owner());
        if (c) return `${c}.<init>`;
        continue;
      }
      default:
        continue;
    }
  }
  return '<module>';
}

// ---------------------------------------------------------------------------------------------
// Scopes and what a name holds

const isMethodScope = (n: JNode): boolean =>
  n.type === 'method_declaration' || n.type === 'constructor_declaration' || n.type === 'compact_constructor_declaration' || n.type === 'static_initializer' || n.type === 'lambda_expression';

/** The nearest enclosing method-like node (lambda included), or null at class level. */
export function enclosingMethod(n: JNode | null): JNode | null {
  for (let p = n; p; p = p.parent) if (isMethodScope(p)) return p;
  return null;
}

/** The nearest enclosing method or constructor that is not a lambda. */
export function enclosingNamedMethod(n: JNode | null): JNode | null {
  for (let p = n; p; p = p.parent) if (isMethodScope(p) && p.type !== 'lambda_expression') return p;
  return null;
}

export function enclosingType(n: JNode | null): JNode | null {
  for (let p = n; p; p = p.parent) if (isTypeDecl(p)) return p;
  return null;
}

/** The statement-level ancestors (blocks) between a node and its method, innermost first. */
export function enclosingBlock(n: JNode): JNode | null {
  for (let p: JNode | null = n.parent; p; p = p.parent) if (p.type === 'block' || p.type === 'constructor_body' || p.type === 'switch_block') return p;
  return null;
}

/** String content of a string literal when it is one plain literal (no concatenation), else null. */
export function plainString(n: JNode | null | undefined): string | null {
  if (!n || n.type !== 'string_literal') return null;
  return literalOf(stringPieces(n));
}

const ESCAPES: Record<string, string> = { n: '\n', t: '\t', r: '\r', b: '\b', f: '\f', s: ' ', '"': '"', "'": "'", '\\': '\\', '0': '\0' };

export function unescapeJava(s: string): string {
  if (s.startsWith('\\u')) {
    const code = Number.parseInt(s.slice(2), 16);
    return Number.isFinite(code) ? String.fromCharCode(code) : s;
  }
  return ESCAPES[s.slice(1)] ?? s;
}

/** Literal text of a `string_literal` (regular or text block). */
export function stringPieces(n: JNode): Piece[] {
  const out: Piece[] = [];
  for (let i = 0; i < n.namedChildCount; i++) {
    const c = n.namedChild(i);
    if (!c) continue;
    if (c.type === 'string_fragment' || c.type === 'multiline_string_fragment') out.push({ k: 'lit', v: c.text });
    else if (c.type === 'escape_sequence') out.push({ k: 'lit', v: unescapeJava(c.text) });
  }
  return mergePieces(out);
}

const ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]{0,127}$/;
const ENV_STYLE = /^[A-Z][A-Z0-9_]{0,127}$/;

/** `System.getenv("X")` and `System.getenv().get("X")`: the env var NAME. */
export function envNameOf(n: JNode): string | null {
  if (n.type !== 'method_invocation') return null;
  const name = nameOf(n);
  const obj = n.childForFieldName('object');
  const args = argsOf(n);
  const lit = (a: JNode | undefined): string | null => {
    const s = a ? plainString(a) : null;
    return s !== null && ENV_NAME.test(s) ? s : null;
  };
  if (name === 'getenv' && obj?.text === 'System' && args.length === 1) return lit(args[0]);
  if (name === 'get' && obj?.type === 'method_invocation' && nameOf(obj) === 'getenv' && obj.childForFieldName('object')?.text === 'System' && argsOf(obj).length === 0) return lit(args[0]);
  return null;
}

/** The env var name inside a Spring `@Value("${NAME}")` / `${NAME:default}` placeholder, only when it is env-shaped. */
export function valueAnnotationEnv(annotations: JNode[]): string | null {
  for (const a of annotations) {
    if (a.type !== 'annotation' || a.childForFieldName('name')?.text !== 'Value') continue;
    const arg = a.childForFieldName('arguments');
    const lit = arg ? children(arg).find((c) => c.type === 'string_literal') : undefined;
    const s = lit ? plainString(lit) : null;
    const m = s ? /^\$\{([A-Za-z0-9_.-]+)(?::[^}]*)?\}$/.exec(s) : null;
    if (m && ENV_STYLE.test(m[1]!)) return m[1]!;
  }
  return null;
}

const annotationsOf = (n: JNode): JNode[] => {
  const mods = n.children.find((c) => c && c.type === 'modifiers');
  return mods ? children(mods).filter((c) => c.type === 'annotation' || c.type === 'marker_annotation') : [];
};

const MAX_DEPTH = 8;

function formatPieces(fmt: Piece[], args: JNode[], depth: number): Piece[] {
  const out: Piece[] = [];
  let ai = 0;
  for (const p of fmt) {
    if (p.k !== 'lit') {
      out.push(p);
      continue;
    }
    let last = 0;
    for (const m of p.v.matchAll(/%(?:\d+\$)?[-#+ 0,(]*\d*(?:\.\d+)?[a-zA-Z%]/g)) {
      if (m.index! > last) out.push({ k: 'lit', v: p.v.slice(last, m.index) });
      if (m[0] === '%%') out.push({ k: 'lit', v: '%' });
      else if (m[0] === '%n') out.push({ k: 'lit', v: '\n' });
      else {
        const a = args[ai++];
        out.push(...(a ? evalPieces(a, depth + 1) : [{ k: 'dyn' } as Piece]));
      }
      last = m.index! + m[0].length;
    }
    if (last < p.v.length) out.push({ k: 'lit', v: p.v.slice(last) });
  }
  return mergePieces(out);
}

/** A string expression as pieces: literals, env var names, dynamic holes. Same-file constants are folded. */
export function evalPieces(n: JNode, depth = 0): Piece[] {
  if (depth > MAX_DEPTH) return [{ k: 'dyn' }];
  switch (n.type) {
    case 'string_literal':
      return stringPieces(n);
    case 'parenthesized_expression': {
      const inner = children(n)[0];
      return inner ? evalPieces(inner, depth + 1) : [{ k: 'dyn' }];
    }
    case 'cast_expression': {
      const v = n.childForFieldName('value');
      return v ? evalPieces(v, depth + 1) : [{ k: 'dyn' }];
    }
    case 'binary_expression': {
      const l = n.childForFieldName('left');
      const r = n.childForFieldName('right');
      if (n.childForFieldName('operator')?.text === '+' && l && r) return mergePieces([...evalPieces(l, depth + 1), ...evalPieces(r, depth + 1)]);
      return [{ k: 'dyn' }];
    }
    case 'identifier':
    case 'field_access': {
      if (n.type === 'field_access' && n.childForFieldName('object')?.type !== 'this') return [{ k: 'dyn' }];
      const name = n.type === 'identifier' ? n.text : (n.childForFieldName('field')?.text ?? '');
      const v = lookupName(name, n);
      if (v && typeof v === 'object' && 'env' in v) return [{ k: 'env', name: v.env }];
      return v && v !== 'opaque' && !('env' in v) ? evalPieces(v, depth + 1) : [{ k: 'dyn' }];
    }
    case 'method_invocation': {
      const env = envNameOf(n);
      if (env) return [{ k: 'env', name: env }];
      const name = nameOf(n);
      const obj = n.childForFieldName('object');
      const args = argsOf(n);
      if (name === 'format' && obj?.text === 'String' && args.length >= 1) return formatPieces(evalPieces(args[0]!, depth + 1), args.slice(1), depth);
      if (name === 'formatted' && obj) return formatPieces(evalPieces(obj, depth + 1), args, depth);
      if (name === 'create' && obj?.text === 'URI' && args.length === 1) return evalPieces(args[0]!, depth + 1);
      if (name === 'valueOf' && obj?.text === 'String' && args.length === 1) return evalPieces(args[0]!, depth + 1);
      if (obj && args.length === 0 && /^(?:toString|trim|strip|intern)$/.test(name)) return evalPieces(obj, depth + 1);
      if (obj && name === 'concat' && args.length === 1) return mergePieces([...evalPieces(obj, depth + 1), ...evalPieces(args[0]!, depth + 1)]);
      return [{ k: 'dyn' }];
    }
    case 'object_creation_expression': {
      const t = n.childForFieldName('type')?.text ?? '';
      const args = argsOf(n);
      if ((t === 'URI' || t === 'URL') && args.length === 1) return evalPieces(args[0]!, depth + 1);
      return [{ k: 'dyn' }];
    }
    default:
      return [{ k: 'dyn' }];
  }
}

/** The plain text when every piece is literal, else null. */
export function literalOf(ps: Piece[]): string | null {
  return ps.every((p) => p.k === 'lit') ? ps.map((p) => (p as { v: string }).v).join('') : null;
}

// ---------------------------------------------------------------------------------------------
// Scope lookup: what does `name` hold at this point?

type Bound = JNode | 'opaque' | { env: string } | null;

interface Bindings {
  values: JNode[];
  opaque: boolean;
  env: string | null;
}

function patternNames(n: JNode | null): Set<string> {
  const out = new Set<string>();
  if (!n) return out;
  walk(n, (c) => {
    if (c.type === 'identifier') out.add(c.text);
  });
  return out;
}

function paramBindings(scope: JNode, name: string): Bindings | null {
  return scopeIndex(scope).parameters.get(name)?.binding ?? null;
}

function paramName(p: JNode): string {
  if (p.type === 'spread_parameter') return children(p).find((c) => c.type === 'variable_declarator')?.childForFieldName('name')?.text ?? '';
  return p.childForFieldName('name')?.text ?? '';
}

interface ScopeIndex {
  locals: Map<string, Bindings>;
  types: Map<string, string | null>;
  parameters: Map<string, { binding: Bindings; type: string | null }>;
}

// Native wrappers are recreated while walking; tree + stable node id names one lexical scope.
// Index all names once, including missing lookups, rather than walking once for each new name.
const SCOPE_INDEX = new WeakMap<Tree, Map<number, ScopeIndex>>();

function scopeIndex(scope: JNode): ScopeIndex {
  let scopes = SCOPE_INDEX.get(scope.tree);
  if (!scopes) { scopes = new Map(); SCOPE_INDEX.set(scope.tree, scopes); }
  const cached = scopes.get(scope.id);
  if (cached) return cached;
  const index: ScopeIndex = { locals: new Map(), types: new Map(), parameters: new Map() };
  const params = scope.childForFieldName('parameters');
  if (scope.type === 'lambda_expression' && params) {
    for (const name of patternNames(params)) index.parameters.set(name, {
      binding: { values: [], opaque: true, env: null }, type: null,
    });
  }
  for (const parameter of params ? children(params) : []) {
    if (parameter.type !== 'formal_parameter' && parameter.type !== 'spread_parameter') continue;
    index.parameters.set(paramName(parameter), {
      binding: { values: [], opaque: true, env: scope.type === 'lambda_expression' ? null : valueAnnotationEnv(annotationsOf(parameter)) },
      type: parameter.childForFieldName('type')?.text ?? null,
    });
  }
  const binding = (name: string): Bindings => {
    let value = index.locals.get(name);
    if (!value) { value = { values: [], opaque: false, env: null }; index.locals.set(name, value); }
    return value;
  };
  const opaquePattern = (node: JNode) => {
    for (const name of patternNames(node)) binding(name).opaque = true;
  };
  const body = scope.childForFieldName('body') ?? scope;
  walk(body, (n) => {
    // a nested type or lambda has its own scope, which lookupName visits itself
    if (n.id !== body.id && (isTypeDecl(n) || n.type === 'lambda_expression' || n.type === 'class_body')) return false;
    switch (n.type) {
      case 'variable_declarator': {
        const name = n.childForFieldName('name')?.text;
        if (!name) break;
        const v = n.childForFieldName('value');
        if (v) binding(name).values.push(v);
        break;
      }
      case 'local_variable_declaration': {
        const type = n.childForFieldName('type')?.text ?? null;
        for (const declaration of n.childrenForFieldName('declarator')) {
          const name = declaration?.childForFieldName('name')?.text;
          if (name) index.types.set(name, type);
        }
        break;
      }
      case 'assignment_expression': {
        const left = n.childForFieldName('left');
        if (left?.type === 'identifier') {
          const b = binding(left.text);
          if (n.childForFieldName('operator')?.text === '=') {
            const r = n.childForFieldName('right');
            if (r) b.values.push(r);
          } else b.opaque = true;
        }
        break;
      }
      case 'enhanced_for_statement': {
        const name = n.childForFieldName('name')?.text;
        if (name) binding(name).opaque = true;
        break;
      }
      case 'catch_formal_parameter':
      case 'resource':
      case 'pattern':
      case 'type_pattern':
        opaquePattern(n);
        break;
      case 'update_expression':
        opaquePattern(n);
        break;
      default:
        break;
    }
    return undefined;
  });
  scopes.set(scope.id, index);
  return index;
}

function localBindings(scope: JNode, name: string): Bindings {
  return scopeIndex(scope).locals.get(name) ?? { values: [], opaque: false, env: null };
}

function pick(b: Bindings): Bound {
  if (b.opaque) return b.env ? { env: b.env } : 'opaque';
  if (b.values.length === 1) return b.values[0]!;
  if (b.values.length > 1) {
    const first = JSON.stringify(evalPieces(b.values[0]!, MAX_DEPTH - 2));
    return b.values.every((v) => JSON.stringify(evalPieces(v, MAX_DEPTH - 2)) === first) ? b.values[0]! : 'opaque';
  }
  return null;
}

interface FieldIndex {
  bindings: Map<string, Bindings>;
  types: Map<string, string | null>;
}
const FIELD_INDEX = new WeakMap<Tree, Map<number, FieldIndex>>();

function fieldIndex(type: JNode): FieldIndex {
  let types = FIELD_INDEX.get(type.tree);
  if (!types) { types = new Map(); FIELD_INDEX.set(type.tree, types); }
  const cached = types.get(type.id);
  if (cached) return cached;
  const index: FieldIndex = { bindings: new Map(), types: new Map() };
  const body = type.childForFieldName('body');
  const finals = new Set<string>();
  for (const m of body ? children(body) : []) {
    if (m.type !== 'field_declaration') continue;
    for (const d of m.childrenForFieldName('declarator')) {
      const name = d?.childForFieldName('name')?.text;
      if (!d || !name) continue;
      let b = index.bindings.get(name);
      if (!b) { b = { values: [], opaque: false, env: null }; index.bindings.set(name, b); }
      const mods = m.children.find((c) => c && c.type === 'modifiers')?.text ?? '';
      if (/\bfinal\b/.test(mods)) finals.add(name);
      const envName = valueAnnotationEnv(annotationsOf(m));
      const v = d.childForFieldName('value');
      if (envName) b.env = envName;
      if (v) b.values.push(v);
      index.types.set(name, m.childForFieldName('type')?.text ?? null);
    }
  }
  // assignments elsewhere in the class (constructors: `this.x = ...`)
  if (body) walk(body, (n) => {
    if (n.type === 'update_expression') {
      for (const name of patternNames(n)) {
        const b = index.bindings.get(name);
        if (b) b.opaque = true;
      }
      return undefined;
    }
    if (n.type !== 'assignment_expression') return undefined;
    const left = n.childForFieldName('left');
    const target = left?.type === 'field_access' && left.childForFieldName('object')?.type === 'this' ? left.childForFieldName('field')?.text : left?.type === 'identifier' ? left.text : null;
    const b = target ? index.bindings.get(target) : undefined;
    if (b) {
      if (n.childForFieldName('operator')?.text !== '=') { b.opaque = true; return undefined; }
      const r = n.childForFieldName('right');
      // a bare constructor parameter of the same name means the value arrives from outside
      if (r) b.values.push(r);
    }
    return undefined;
  });
  for (const [name, b] of index.bindings) {
    if (b.env) { b.values = []; b.opaque = true; }
    else if (!finals.has(name) && b.values.length !== 1) b.opaque = true;
  }
  for (const parameter of type.childForFieldName('parameters') ? children(type.childForFieldName('parameters')!) : []) {
    if (parameter.type === 'formal_parameter') index.types.set(paramName(parameter), parameter.childForFieldName('type')?.text ?? null);
  }
  types.set(type.id, index);
  return index;
}

/** Fields of the class (and outer classes) named `name`: initializer values, @Value env names, assignments. */
function fieldBindings(type: JNode, name: string): Bindings | null {
  return fieldIndex(type).bindings.get(name) ?? null;
}

/**
 * The expression a name holds at `at`: a single initializer/assignment in the nearest scope that binds
 * it, `{env}` when it is a `@Value("${SWFTE_X}")` field or parameter, 'opaque' when it arrives from outside
 * (a parameter, a loop variable, reassigned differently), null when no scope binds it.
 */
export function lookupName(name: string, at: JNode): Bound {
  for (let s = enclosingMethod(at); s; s = enclosingMethod(s.parent)) {
    const pb = paramBindings(s, name);
    if (pb) return pick(pb);
    const b = localBindings(s, name);
    if (b.opaque || b.values.length > 0) return pick(b);
  }
  for (let t = enclosingType(at); t; t = enclosingType(t.parent)) {
    const fb = fieldBindings(t, name);
    if (fb) {
      const r = pick(fb);
      return r === null ? 'opaque' : r;
    }
  }
  return null;
}

/** The declared type text of the parameter, local or field `name` as seen from `at`, or null when unknown. */
export function declaredType(name: string, at: JNode): string | null {
  for (let s = enclosingMethod(at); s; s = enclosingMethod(s.parent)) {
    const index = scopeIndex(s);
    const parameter = index.parameters.get(name);
    if (parameter) return parameter.type;
    if (index.types.has(name)) return index.types.get(name) ?? null;
    const local = index.locals.get(name);
    if (local && (local.opaque || local.values.length > 0)) return null;
  }
  for (let t = enclosingType(at); t; t = enclosingType(t.parent)) {
    const fields = fieldIndex(t);
    if (fields.types.has(name)) return fields.types.get(name) ?? null;
  }
  return null;
}

/** All expressions assigned to (or initialising) the field `name` in the nearest class declaring it. */
export function fieldValues(name: string, at: JNode): JNode[] {
  for (let t = enclosingType(at); t; t = enclosingType(t.parent)) {
    const fb = fieldBindings(t, name);
    if (fb) return fb.values;
  }
  return [];
}

/** Whether the file references the Swfte SDK package, and whether a same-named fork class is imported. */
export function swfteImports(root: JNode): { swfte: boolean; fork: boolean } {
  let swfte = false;
  let fork = false;
  walk(root, (n) => {
    if (n.type === 'import_declaration') {
      const t = n.text.replace(/^import\s+(?:static\s+)?/, '').replace(/;\s*$/, '').trim();
      if (/^com\.swfte\.sdk\b/.test(t)) swfte = true;
      else if (/(?:^|\.)SwfteClient$/.test(t)) fork = true;
      return false;
    }
    if (n.type === 'scoped_type_identifier' || n.type === 'scoped_identifier' || n.type === 'field_access') {
      if (/^com\.swfte\.sdk\b/.test(n.text)) swfte = true;
    }
    return undefined;
  });
  return { swfte, fork };
}
