// Generated by @swfte/mcp-server (swfte add / swfte_scaffold_client). Do not edit by hand — run `swfte sync`.
// Source of truth: Swfte Studio catalog entry workflow:wf_8K2mQ4
// Artifact: Content pipeline
// Drafts articles on a topic from a list of source URLs.
// Contract hash: 874bedbbe106b7aeb432fd72bc399c558f7afd95ba01c1e5ecda9f8fe7bb2202 (recorded in swfte.json; a different hash means the contract moved).
// Pinned to published version 3: a newer publish upstream does not change what this client runs.
// `swfte upgrade content-pipeline` moves the pin (after the breaking/re-approval checks).
//
// Server-side only: reads SWFTE_API_KEY from the environment. Never bundle this file into browser code.
// Configure via .env: SWFTE_API_KEY, SWFTE_BASE_URL, SWFTE_WORKSPACE_ID.

export const CATALOG_REF = "workflow:wf_8K2mQ4";
export const CONTRACT_HASH = "874bedbbe106b7aeb432fd72bc399c558f7afd95ba01c1e5ecda9f8fe7bb2202";
/** Published version this client runs (null: unpinned, runs the latest published version). */
export const PINNED_VERSION: string | null = "3";
/** Identifies this generated client to Swfte (counts adopter runs; never carries payloads). */
export const SWFTE_CLIENT = "typescript/0.2.0; ref=workflow:wf_8K2mQ4; hash=874bedbbe106b7aeb432fd72bc399c558f7afd95ba01c1e5ecda9f8fe7bb2202";
// swfte-shape: {"in":{"maxWords":"integer","sources":"array!","topic":"string!"},"out":{"articles":"array","runId":"string","status":"string"}}

const INVOKE: { method: string; path: string; auth: "pat" | "api_key" | "public"; async: boolean; statusPath: string | null } = {
  method: "POST",
  path: "/v2/workflows/wf_8K2mQ4/versions/3/invoke",
  auth: "api_key",
  async: true,
  statusPath: "/v2/workflows/executions/{executionId}/status",
};

export type ContentPipelineInput = {
  sources: Array<string>;
  topic: string;
  maxWords?: number;
};

export type ContentPipelineOutput = {
  runId?: string;
  articles?: Array<Record<string, unknown>>;
  status?: string;
  [key: string]: unknown;
};

export interface InvokeResult<T> {
  /** True when the call (and, for async artifacts, the run) completed successfully. */
  ok: boolean;
  /** Terminal status, "WAITING_FOR_INPUT"-style pause, or "ACCEPTED" when there is no status to poll. */
  status: string;
  executionId?: string;
  output: T | undefined;
  raw: unknown;
}

export interface ClientOptions {
  /** Defaults to process.env.SWFTE_API_KEY. A PAT (pat_…) or API key (sk-swfte-…). */
  apiKey?: string;
  /** Defaults to process.env.SWFTE_BASE_URL, then "https://api.swfte.com/agents". */
  baseUrl?: string;
  /** Defaults to process.env.SWFTE_WORKSPACE_ID. Sent with API keys; PATs carry their own binding. */
  workspaceId?: string;
  /** Overall budget for invoke + polling. Default 300000 ms. */
  timeoutMs?: number;
  /** Delay between status polls. Default 2000 ms. */
  pollIntervalMs?: number;
  fetch?: typeof fetch;
}

export class SwfteRequestError extends Error {
  constructor(readonly status: number, readonly body: string, readonly path: string) {
    super(`Swfte request failed: ${status} on ${path}: ${body.slice(0, 300)}`);
    this.name = 'SwfteRequestError';
  }
}

const TERMINAL = new Set(["COMPLETED","SUCCEEDED","SUCCESS","FAILED","FAILURE","ERROR","CANCELLED","CANCELED","TIMEOUT","TIMED_OUT","TERMINATED","REJECTED"]);
const WAITING = new Set(["PAUSED","WAITING_FOR_INPUT","AWAITING_HUMAN"]);
const SUCCESS = new Set(["COMPLETED","SUCCEEDED","SUCCESS"]);

function env(name: string): string | undefined {
  // globalThis keeps this compiling in projects without @types/node.
  return (globalThis as any).process?.env?.[name];
}

function fill(path: string, values: Record<string, string>): string {
  return path.replace(/\{([A-Za-z_][A-Za-z0-9_]*)\}/g, (_m, key: string) => {
    const v = values[key];
    if (v === undefined || v === '') throw new Error(`Missing value for path placeholder {${key}}`);
    return encodeURIComponent(v);
  });
}

async function call(opts: ClientOptions, method: string, path: string, body: unknown, deadline: number): Promise<any> {
  const f = opts.fetch ?? fetch;
  const baseUrl = (opts.baseUrl ?? env('SWFTE_BASE_URL') ?? "https://api.swfte.com/agents").replace(/\/+$/, '');
  const headers: Record<string, string> = { Accept: 'application/json', 'X-Swfte-Client': SWFTE_CLIENT };
  if (INVOKE.auth !== 'public') {
    const key = opts.apiKey ?? env('SWFTE_API_KEY');
    if (!key) throw new Error('SWFTE_API_KEY is not set (see .env.example).');
    headers.Authorization = `Bearer ${key}`;
    if (!key.startsWith('pat_')) {
      headers['X-API-Key'] = key;
      const ws = opts.workspaceId ?? env('SWFTE_WORKSPACE_ID');
      if (ws) headers['X-Workspace-ID'] = ws;
    }
  }
  let url = baseUrl + path;
  let payload: string | undefined;
  if (body !== undefined) {
    if (method === 'GET') {
      const qs = new URLSearchParams();
      for (const [k, v] of Object.entries(body as Record<string, unknown>)) if (v !== undefined && v !== null) qs.set(k, String(v));
      const s = qs.toString();
      if (s) url += (url.includes('?') ? '&' : '?') + s;
    } else {
      headers['Content-Type'] = 'application/json';
      payload = JSON.stringify(body);
    }
  }
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), Math.max(1, deadline - Date.now()));
  try {
    const res = await f(url, { method, headers, body: payload, signal: controller.signal });
    const text = await res.text();
    if (!res.ok) throw new SwfteRequestError(res.status, text, path);
    if (!text) return undefined;
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  } finally {
    clearTimeout(timer);
  }
}

const statusOf = (s: any): string => String(s?.execution?.status ?? s?.status ?? 'UNKNOWN').toUpperCase();
const outputOf = (s: any): unknown => s?.execution?.outputData ?? s?.outputData ?? s?.output ?? s?.result;

/**
 * Drafts articles on a topic from a list of source URLs.
 */
export async function invokeContentPipeline(input: ContentPipelineInput, opts: ClientOptions = {}): Promise<InvokeResult<ContentPipelineOutput>> {
  const deadline = Date.now() + (opts.timeoutMs ?? 300_000);
  const path = fill(INVOKE.path, {  });
  const started = await call(opts, INVOKE.method, path, input, deadline);
  if (!INVOKE.async) {
    return { ok: true, status: 'COMPLETED', output: started as ContentPipelineOutput, raw: started };
  }
  const executionId = String(started?.executionId ?? started?.execution?.id ?? started?.id ?? '');
  if (!executionId || !INVOKE.statusPath) {
    return { ok: false, status: 'ACCEPTED', executionId: executionId || undefined, output: undefined, raw: started };
  }
  const statusPath = fill(INVOKE.statusPath, { executionId, id: executionId });
  for (;;) {
    const snapshot = await call(opts, 'GET', statusPath, undefined, deadline);
    const status = statusOf(snapshot);
    if (TERMINAL.has(status) || WAITING.has(status)) {
      return { ok: SUCCESS.has(status), status, executionId, output: outputOf(snapshot) as ContentPipelineOutput | undefined, raw: snapshot };
    }
    if (Date.now() + (opts.pollIntervalMs ?? 2_000) > deadline) {
      throw new Error(`Timed out waiting for execution ${executionId} (last status ${status}). It may still finish; poll ${statusPath}.`);
    }
    await new Promise((r) => setTimeout(r, opts.pollIntervalMs ?? 2_000));
  }
}
// swfte-checksum: b26b2c4d18ada50b
