/**
 * Python parsing for the code map detectors (docs/codemap/CONTRACT.md §2.1, §7). One `web-tree-sitter`
 * parser over the vendored grammar, initialised once at import time (top-level await) because
 * `Detector.detect` is synchronous. Source text stays in this process and is never serialised.
 *
 * Everything here is structural: symbols, scope lookups, string templates. A value the code does not
 * spell out in a literal is reported as dynamic, never guessed.
 */
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Language, Parser, type Node, type Tree } from 'web-tree-sitter';
import { mergePieces, type Piece } from './route.js';
import { initRuntime } from './runtime.js';

export type PyNode = Node;

const DEFAULT_WASM = fileURLToPath(new URL('../../grammars/tree-sitter-python.wasm', import.meta.url));
let parser: Parser | null = null;
/** Bumps every time the grammar is (re)loaded, so per-file caches never outlive their parser. */
export let grammarGeneration = 0;

/**
 * (Re)load the Python grammar. Returns false, leaving no parser, when the WASM cannot be read or
 * loaded: detectors then report nothing and the scan goes on (edge case E9).
 */
export async function initPythonParser(wasmPath: string = DEFAULT_WASM): Promise<boolean> {
  try {
    await initRuntime();
    const language = await Language.load(fs.readFileSync(wasmPath));
    const p = new Parser();
    p.setLanguage(language);
    parser = p;
    grammarGeneration++;
    return true;
  } catch {
    parser = null;
    grammarGeneration++;
    return false;
  }
}

await initPythonParser();

/** Parse and hand the tree to `fn`; the native tree is always freed. Null when no grammar is loaded. */
export function withTree<T>(text: string, fn: (root: PyNode) => T): T | null {
  if (!parser) return null;
  let tree: Tree | null = null;
  try {
    tree = parser.parse(text);
    if (!tree) return null;
    return fn(tree.rootNode);
  } catch {
    return null;
  } finally {
    if (tree) {
      // Cached Nodes reference this Tree and its source callback. Their lifetime ends here.
      NAMED_CHILDREN_CACHE.delete(tree);
      BINDINGS_CACHE.delete(tree);
      tree.delete();
    }
  }
}

// ---------------------------------------------------------------------------------------------
// Paths that never hold call sites (decoys): tests, mocks, vendored and generated trees.

const VENDORED_DIRS = new Set(['.venv', 'venv', 'site-packages', '__pycache__', 'node_modules', 'target', 'build', 'dist', '.git', '.tox']);

export function isIgnoredPath(relPath: string): boolean {
  const segs = relPath.split('/');
  const base = segs[segs.length - 1] ?? '';
  if (segs.slice(0, -1).some((s) => VENDORED_DIRS.has(s) || s === 'tests' || s === 'test' || s === '__tests__' || s === '__mocks__' || s === 'testing')) return true;
  return /^test_.*\.py$/.test(base) || /_tests?\.py$/.test(base) || base === 'conftest.py';
}

/** Another tool's generated marker in the header (the Swfte generated client has its own marker). */
export function isForeignGenerated(text: string): boolean {
  const head = text.slice(0, 4096).split(/\r?\n/).slice(0, 40).join('\n');
  if (/Generated by @swfte\//.test(head)) return false;
  return /@generated\b/.test(head) || /Code generated\b.*\bDO NOT EDIT\b/.test(head);
}

/** A module that imports a mocking or test framework is a test even when it sits in a main tree. */
export function usesMocks(root: PyNode): boolean {
  for (const st of children(root)) {
    if (st.type !== 'import_statement' && st.type !== 'import_from_statement') continue;
    if (/^(?:from|import)\s+(?:unittest|pytest|pytest_mock|mock)\b/.test(st.text)) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------------------------
// Tree helpers

/** A node in (or containing) a syntax error: edge case E8 says a broken region yields no sites. */
export function isBroken(n: PyNode): boolean {
  if (n.hasError || n.isMissing) return true;
  for (let p = n.parent; p; p = p.parent) if (p.type === 'ERROR') return true;
  return false;
}

export const lineOf = (n: PyNode): number => n.startPosition.row + 1;

const EMPTY_NAMED_CHILDREN: readonly PyNode[] = Object.freeze([] as PyNode[]);
const NAMED_CHILDREN_CACHE = new WeakMap<Tree, Map<number, readonly PyNode[]>>();

/** Native getters create fresh wrappers; detector passes share immutable vectors inside one tree. */
function namedChildren(n: PyNode): readonly PyNode[] {
  let nodes = NAMED_CHILDREN_CACHE.get(n.tree);
  const cached = nodes?.get(n.id);
  if (cached) return cached;
  const count = n.namedChildCount;
  if (count === 0) return EMPTY_NAMED_CHILDREN;
  const out: PyNode[] = [];
  for (let i = 0; i < count; i++) {
    const c = n.namedChild(i);
    if (c) out.push(c);
  }
  if (!nodes) { nodes = new Map(); NAMED_CHILDREN_CACHE.set(n.tree, nodes); }
  const vector = Object.freeze(out);
  nodes.set(n.id, vector);
  return vector;
}

export function children(n: PyNode): PyNode[] {
  return [...namedChildren(n)];
}

/** Depth-first walk over named nodes; `visit` returning false prunes the subtree. */
export function walk(n: PyNode, visit: (n: PyNode) => boolean | void): void {
  if (visit(n) === false) return;
  for (const child of namedChildren(n)) walk(child, visit);
}

/** `Class.method`, `func`, `outer.inner`, `<module>`; lambdas and comprehensions add nothing (D2). */
export function symbolOf(n: PyNode): string {
  const names: string[] = [];
  for (let p: PyNode | null = n.parent; p; p = p.parent) {
    if (p.type === 'function_definition' || p.type === 'class_definition') {
      const nm = p.childForFieldName('name');
      if (nm) names.push(nm.text);
    }
  }
  return names.length ? names.reverse().join('.') : '<module>';
}

function isScope(n: PyNode): boolean {
  return n.type === 'function_definition' || n.type === 'module';
}

export function enclosingScope(n: PyNode | null): PyNode | null {
  for (let p = n; p; p = p.parent) if (isScope(p)) return p;
  return null;
}

// ---------------------------------------------------------------------------------------------
// String templates

export type { Piece };

const ESCAPES: Record<string, string> = { n: '\n', t: '\t', r: '\r', '"': '"', "'": "'", '\\': '\\' };

function unescapePy(s: string): string {
  return s.replace(/\\(.)/g, (_m, c: string) => ESCAPES[c] ?? `\\${c}`);
}

function stringPrefix(n: PyNode): string {
  const start = n.child(0);
  return start && start.type === 'string_start' ? start.text.replace(/["']+$/, '').toLowerCase() : '';
}

/** Literal text and holes of a `string` node; f-string holes are evaluated as expressions. */
function stringPieces(n: PyNode, depth: number): Piece[] {
  const prefix = stringPrefix(n);
  const isF = prefix.includes('f');
  const isRaw = prefix.includes('r');
  const out: Piece[] = [];
  for (let i = 0; i < n.childCount; i++) {
    const c = n.child(i);
    if (!c) continue;
    if (c.type === 'string_content') {
      let v = c.text;
      if (isF) v = v.replace(/\{\{/g, '{').replace(/\}\}/g, '}');
      out.push({ k: 'lit', v: isRaw ? v : unescapePy(v) });
    } else if (c.type === 'interpolation') {
      const e = c.childForFieldName('expression');
      out.push(...(e ? evalPieces(e, depth + 1) : [{ k: 'dyn' } as Piece]));
    }
  }
  return out;
}

const ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]{0,127}$/;

/** `os.environ["X"]`, `os.environ.get("X", d)`, `os.getenv("X", d)`, `environ[...]`: the env var NAME. */
export function envNameOf(n: PyNode): string | null {
  const stringArg = (a: PyNode | null): string | null => {
    if (!a || a.type !== 'string') return null;
    const ps = stringPieces(a, 0);
    return ps.length === 1 && ps[0]!.k === 'lit' && ENV_NAME.test(ps[0]!.v) ? ps[0]!.v : null;
  };
  const isEnviron = (o: PyNode | null): boolean => !!o && /^(?:os\.)?environ$/.test(o.text);
  if (n.type === 'subscript') {
    const v = n.childForFieldName('value');
    const sub = n.childForFieldName('subscript');
    return isEnviron(v) ? stringArg(sub) : null;
  }
  if (n.type === 'call') {
    const f = n.childForFieldName('function');
    const args = n.childForFieldName('arguments');
    const first = args ? children(args).find((c) => c.type !== 'keyword_argument') ?? null : null;
    if (!f) return null;
    if (/^(?:os\.)?getenv$/.test(f.text)) return stringArg(first);
    if (f.type === 'attribute' && f.childForFieldName('attribute')?.text === 'get' && isEnviron(f.childForFieldName('object'))) return stringArg(first);
  }
  return null;
}

const MAX_DEPTH = 8;

export function evalPieces(n: PyNode, depth = 0): Piece[] {
  if (depth > MAX_DEPTH) return [{ k: 'dyn' }];
  switch (n.type) {
    case 'string':
      return mergePieces(stringPieces(n, depth));
    case 'concatenated_string':
      return mergePieces(children(n).flatMap((c) => evalPieces(c, depth + 1)));
    case 'parenthesized_expression': {
      const inner = children(n)[0];
      return inner ? evalPieces(inner, depth + 1) : [{ k: 'dyn' }];
    }
    case 'binary_operator': {
      const op = n.childForFieldName('operator')?.text;
      const l = n.childForFieldName('left');
      const r = n.childForFieldName('right');
      if (op === '+' && l && r) return mergePieces([...evalPieces(l, depth + 1), ...evalPieces(r, depth + 1)]);
      return [{ k: 'dyn' }];
    }
    case 'identifier': {
      const v = lookupName(n.text, n);
      return v && v !== 'opaque' ? evalPieces(v, depth + 1) : [{ k: 'dyn' }];
    }
    case 'subscript':
    case 'call': {
      const env = envNameOf(n);
      if (env) return [{ k: 'env', name: env }];
      if (n.type === 'call') {
        // "x".rstrip("/") and friends keep the receiver's text.
        const f = n.childForFieldName('function');
        if (f?.type === 'attribute' && /^(?:rstrip|lstrip|strip)$/.test(f.childForFieldName('attribute')?.text ?? '')) {
          const o = f.childForFieldName('object');
          if (o) return evalPieces(o, depth + 1);
        }
      }
      return [{ k: 'dyn' }];
    }
    default:
      return [{ k: 'dyn' }];
  }
}

/** The plain text when every piece is literal, else null. */
export function literalOf(ps: Piece[]): string | null {
  return ps.length && ps.every((p) => p.k === 'lit') ? ps.map((p) => (p as { v: string }).v).join('') : ps.length === 0 ? '' : null;
}

/** A string expression only when the whole thing is one literal (no f-string hole, no concatenation). */
export function plainString(n: PyNode | null | undefined): string | null {
  if (!n || n.type !== 'string') return null;
  const ps = stringPieces(n, 0);
  return ps.every((p) => p.k === 'lit') ? ps.map((p) => (p as { v: string }).v).join('') : null;
}

// ---------------------------------------------------------------------------------------------
// Scope lookup: what does `name` hold at this point?

function paramNames(fn: PyNode): Set<string> {
  const out = new Set<string>();
  const params = fn.childForFieldName('parameters');
  if (!params) return out;
  walk(params, (c) => {
    if (c.type === 'identifier') {
      const p = c.parent;
      // default values and annotations are expressions, not bindings
      if (p && (p.type === 'default_parameter' || p.type === 'typed_default_parameter') && p.childForFieldName('name')?.id !== c.id) return;
      if (p && p.type === 'typed_parameter' && p.childCount > 0 && p.child(0)?.id !== c.id) return;
      out.add(c.text);
    } else if (c.type === 'default_parameter' || c.type === 'typed_default_parameter') {
      const nm = c.childForFieldName('name');
      if (nm) out.add(nm.text);
      return false;
    }
    return undefined;
  });
  return out;
}

function patternBinds(p: PyNode | null, name: string): boolean {
  if (!p) return false;
  let hit = false;
  walk(p, (c) => {
    if (c.type === 'identifier' && c.text === name) hit = true;
  });
  return hit;
}

interface Bindings {
  values: PyNode[];
  opaque: boolean;
}

// Index every name in a lexical scope once, including negative lookups. Caching one name at a
// time still walks the whole scope for each distinct call-site variable and remains quadratic.
const BINDINGS_CACHE = new WeakMap<Tree, Map<number, Map<string, Bindings>>>();

function bindingsIn(scope: PyNode, name: string): Bindings {
  let scopes = BINDINGS_CACHE.get(scope.tree);
  if (!scopes) {
    scopes = new Map();
    BINDINGS_CACHE.set(scope.tree, scopes);
  }
  let names = scopes.get(scope.id);
  if (!names) {
    names = indexBindings(scope);
    scopes.set(scope.id, names);
  }
  return names.get(name) ?? { values: [], opaque: false };
}

function indexBindings(scope: PyNode): Map<string, Bindings> {
  const names = new Map<string, Bindings>();
  const binding = (name: string): Bindings => {
    let value = names.get(name);
    if (!value) {
      value = { values: [], opaque: false };
      names.set(name, value);
    }
    return value;
  };
  const opaquePattern = (node: PyNode | null) => {
    if (!node) return;
    walk(node, (part) => { if (part.type === 'identifier') binding(part.text).opaque = true; });
  };
  const visit = (n: PyNode): boolean | void => {
    if (n.id !== scope.id && (n.type === 'function_definition' || n.type === 'class_definition')) {
      const name = n.childForFieldName('name')?.text;
      if (name) binding(name).opaque = true;
      return false;
    }
    switch (n.type) {
      case 'lambda':
        return false;
      case 'assignment': {
        const left = n.childForFieldName('left');
        const right = n.childForFieldName('right');
        if (left?.type === 'identifier') {
          const b = binding(left.text);
          if (right) b.values.push(right);
          else b.opaque = true;
        } else if (left && left.type !== 'attribute' && left.type !== 'subscript') opaquePattern(left);
        break;
      }
      case 'augmented_assignment':
        opaquePattern(n.childForFieldName('left'));
        break;
      case 'for_statement':
      case 'for_in_clause':
        opaquePattern(n.childForFieldName('left'));
        break;
      case 'as_pattern':
      case 'with_item':
        for (const child of n.children) if (child?.type === 'as_pattern_target') opaquePattern(child);
        break;
      case 'as_pattern_target':
        opaquePattern(n);
        break;
      case 'named_expression':
        {
          const name = n.childForFieldName('name')?.text;
          if (name) binding(name).opaque = true;
        }
        break;
      case 'import_statement':
      case 'import_from_statement':
        for (const name of n.text.split(/[\s,()]+/)) if (name) binding(name).opaque = true;
        break;
      case 'global_statement':
      case 'nonlocal_statement':
        opaquePattern(n);
        break;
      default:
        break;
    }
    return undefined;
  };
  walk(scope, visit);
  return names;
}

/**
 * The expression a name holds when exactly one (or several equal-text) assignments in the nearest
 * scope that binds it provide a value; 'opaque' when it is a parameter, a loop variable, reassigned
 * with different values, etc.; null when no enclosing scope binds it.
 */
export function lookupName(name: string, at: PyNode): PyNode | 'opaque' | null {
  for (let s = enclosingScope(at); s; s = enclosingScope(s.parent)) {
    if (s.type === 'function_definition' && paramNames(s).has(name)) return 'opaque';
    const b = bindingsIn(s, name);
    if (b.opaque) return 'opaque';
    if (b.values.length === 1) return b.values[0]!;
    if (b.values.length > 1) {
      const first = JSON.stringify(evalPieces(b.values[0]!, MAX_DEPTH - 2));
      return b.values.every((v) => JSON.stringify(evalPieces(v, MAX_DEPTH - 2)) === first) ? b.values[0]! : 'opaque';
    }
  }
  return null;
}

/** Whether the file imports a module whose dotted path names swfte, and whether any names a fork. */
export function swfteImports(root: PyNode): { swfte: boolean; fork: boolean } {
  let swfte = false;
  let fork = false;
  for (const st of children(root)) {
    if (st.type !== 'import_statement' && st.type !== 'import_from_statement') continue;
    const mod = st.type === 'import_from_statement' ? st.childForFieldName('module_name')?.text ?? '' : st.text.replace(/^import\s+/, '');
    const all = `${mod} ${st.text}`.toLowerCase();
    if (/swfte/.test(all)) swfte = true;
    if (/fork/.test(mod.toLowerCase())) fork = true;
  }
  return { swfte, fork };
}
