/**
 * Bake-in (CONTRACT rev 4): the one implementation behind both the MCP tools
 * (swfte_scaffold_client, swfte_sync, swfte_check_upgrades) and the `swfte`
 * CLI (add, sync, verify, upgrade). Nothing here prints or exits — callers
 * present results — so the CLI and the tools cannot drift apart.
 *
 * A baked artifact is three things: a generated typed client (owned by Swfte,
 * regenerated by sync, checksummed so hand edits are detected), an optional
 * framework adapter (owned by the developer, never rewritten), and a row in
 * swfte.json pinning the contract hash it was generated against.
 */
import { existsSync, readFileSync } from 'node:fs';
import { posix } from 'node:path';
import {
  effectiveContractHash,
  getContract,
  getEntry,
  parseCatalogRef,
  sameHash,
  type CatalogContract,
  type CatalogEntryDetail,
} from './catalog.js';
import type { SwfteClient } from './client.js';
import { SwfteApiError } from './client.js';
import {
  clientInfo,
  describeDiff,
  diffShapes,
  inspectGenerated,
  kebab,
  readShape,
  renderPythonClient,
  renderTypeScriptClient,
  snake,
  specShape,
  type ClientSpec,
  type ShapeDiff,
} from './codegen.js';
import { planAdapter } from './adapters.js';
import type { ServerConfig } from './config.js';
import { assertLockBaseUrl } from './hosts.js';
import type { ConfinedWriter, PlannedWrite } from './fsguard.js';
import {
  assertAlias,
  loadLock,
  LOCK_FILE,
  LockError,
  normalizeRel,
  planLockWrite,
  upsertArtifact,
  type Lock,
  type LockArtifact,
} from './lock.js';
import { fixturePath } from './devserver.js';
import { detectStack, FRAMEWORKS, languageOf, type Framework, type Language, type StackDetection } from './stack.js';

export const CLIENT_ENV = [
  { key: 'SWFTE_API_KEY', value: '', comment: 'Swfte PAT (pat_…) or workspace API key (sk-swfte-…). Server-side only; never commit the real value.' },
  { key: 'SWFTE_BASE_URL', value: '', comment: 'Optional. Defaults to the Swfte cloud API.' },
  { key: 'SWFTE_WORKSPACE_ID', value: '', comment: 'Optional with a PAT (the token carries its workspace); used with API keys.' },
];

export interface BakeContext {
  client: SwfteClient;
  config: ServerConfig;
  writer: ConfinedWriter;
  /** Environment for the credential-host allow-list (SWFTE_ALLOWED_HOSTS). Default process.env. */
  env?: NodeJS.ProcessEnv;
}

/* ── layout ──────────────────────────────────────────────────────────────── */

/** Where generated clients go when the caller does not say. */
export function defaultOutDir(framework: Framework, det: StackDetection | null): string {
  const src = det?.layout.hasSrcDir ?? false;
  switch (framework) {
    case 'nextjs':
      return src || det?.layout.appDir === 'src/app' ? 'src/lib/swfte' : 'lib/swfte';
    case 'express':
    case 'plain-ts':
      return src ? 'src/swfte' : 'swfte';
    case 'fastapi':
    case 'plain-python':
      // Never a bare `swfte` package: it would shadow the Swfte Python SDK (`import swfte`).
      return det?.layout.pythonPackage ? `${det.layout.pythonPackage}/swfte_clients` : 'swfte_clients';
  }
}

function clientFileName(alias: string, language: Language): string {
  return language === 'typescript' ? `${alias}.ts` : `${snake(alias, 'artifact')}.py`;
}

function buildSpec(
  config: ServerConfig,
  ref: string,
  alias: string,
  detail: CatalogEntryDetail,
  contract: CatalogContract,
  hash: string,
  baseUrl: string,
  env: NodeJS.ProcessEnv = process.env
): ClientSpec {
  const r = parseCatalogRef(ref);
  // The lock's baseUrl becomes the generated client's DEFAULT_BASE_URL, which
  // receives the application's key at runtime: vet it like the CLI does (H1).
  if (baseUrl) assertLockBaseUrl(baseUrl, env, config.baseUrl);
  return {
    catalogRef: r.ref,
    kind: r.kind,
    id: detail.id ?? r.id,
    name: detail.name || r.id,
    alias,
    description: detail.description ?? null,
    contract,
    contractHash: hash,
    defaultBaseUrl: baseUrl || config.baseUrl,
    pinnedVersion: String(contract.invoke?.path ?? '').includes('/versions/') ? contract.version ?? null : null,
  };
}

function render(spec: ClientSpec, language: Language): string {
  return language === 'typescript' ? renderTypeScriptClient(spec) : renderPythonClient(spec);
}

async function fetchBoth(client: SwfteClient, ref: string) {
  const r = parseCatalogRef(ref);
  const [detail, contract] = await Promise.all([getEntry(client, r), getContract(client, r)]);
  if (!contract || typeof contract !== 'object' || !contract.invoke) {
    throw new Error(`${r.ref} has no invocation contract, so there is nothing to generate a client from. Reuse it inside Studio instead.`);
  }
  return { detail, contract };
}

/* ── version pins (CONTRACT rev 8b) ───────────────────────────────────────── */

/**
 * A pin is a *published* workflow version: `POST /v2/workflows/{id}/versions/{version}/invoke`
 * runs that snapshot even after newer publishes, so an upstream publish never
 * changes what adopters' code calls until `swfte upgrade` moves the pin.
 * Only workflows have versioned invoke; other kinds stay unpinned (null).
 */
export function isPinnable(ref: string, pinnedVersion: string | null | undefined): pinnedVersion is string {
  if (!pinnedVersion || parseCatalogRef(ref).kind !== 'workflow') return false;
  // Older locks recorded the artifact's updatedAt here for information; a timestamp is not a published version.
  return !/^\d{4}-\d{2}-\d{2}T/.test(pinnedVersion);
}

export function versionedInvokePath(id: string, version: string): string {
  return `/v2/workflows/${encodeURIComponent(id)}/versions/${encodeURIComponent(version)}/invoke`;
}

/** The contract a pinned client is generated from: same schemas, invoke path naming the version. */
function pinContract(contract: CatalogContract, id: string, version: string): CatalogContract {
  return { ...contract, invoke: { ...contract.invoke, path: versionedInvokePath(id, version) }, version };
}

export type PinLookup =
  | { state: 'published'; contract: CatalogContract }
  | { state: 'not-published'; detail: string }
  | { state: 'gone'; detail: string }
  | { state: 'unsupported'; detail: string };

/**
 * GET /v2/workflows/{id}/versions/{version}/schema: the contract of one pinned
 * published version. 404 VERSION_NOT_PUBLISHED means that version is not (or no
 * longer) published; a 404 naming the workflow means it is gone; any other 404
 * (an older backend without the route) is "unsupported".
 */
export async function lookupPinnedVersion(client: SwfteClient, ref: string, version: string, fallback: CatalogContract): Promise<PinLookup> {
  const r = parseCatalogRef(ref);
  let body: Record<string, unknown> | undefined;
  try {
    body = await client.request<Record<string, unknown>>({
      method: 'GET',
      path: `/v2/workflows/${encodeURIComponent(r.id)}/versions/${encodeURIComponent(version)}/schema`,
    });
  } catch (err) {
    if (err instanceof SwfteApiError && err.status === 404) {
      if (err.code === 'VERSION_NOT_PUBLISHED') return { state: 'not-published', detail: `version ${version} of ${ref} is not published` };
      if (/WORKFLOW_NOT_FOUND|^NOT_FOUND$/.test(err.code)) return { state: 'gone', detail: `${ref} was not found` };
      return { state: 'unsupported', detail: `this Swfte backend cannot serve pinned versions (${err.code})` };
    }
    throw err;
  }
  if (!body || typeof body !== 'object' || Array.isArray(body)) throw new Error(`Swfte's pinned-version schema for ${ref}@${version} was not a JSON object.`);
  // Never substitute the latest contract's schemas for a pinned version's: that would type the client for the wrong version.
  if (!('inputSchema' in body) || !('outputSchema' in body)) return { state: 'unsupported', detail: `Swfte returned no schemas for ${ref}@${version}` };
  const inv = body.invoke && typeof body.invoke === 'object' ? (body.invoke as CatalogContract['invoke']) : null;
  const pinned = pinContract(
    {
      ...fallback,
      inputSchema: (body.inputSchema as CatalogContract['inputSchema']) ?? fallback.inputSchema,
      outputSchema: (body.outputSchema as CatalogContract['outputSchema']) ?? fallback.outputSchema,
      contractHash: null,
    },
    r.id,
    version
  );
  if (inv && typeof inv.path === 'string' && inv.path.includes('/versions/')) pinned.invoke = { ...pinned.invoke, ...inv };
  return { state: 'published', contract: pinned };
}

/* ── add ─────────────────────────────────────────────────────────────────── */

export interface BakeInput {
  catalogRef: string;
  framework?: Framework;
  language?: Language;
  /** Directory for the generated client, relative to the project root. */
  outDir?: string;
  alias?: string;
  force?: boolean;
  /** Pin the current published version (default true; workflows only). false: the client calls /invoke (latest published). */
  pin?: boolean;
}

export interface BakeResult {
  catalogRef: string;
  alias: string;
  language: Language;
  framework: Framework;
  outDir: string;
  detection: { framework: Framework; detected: string; signals: string[] } | null;
  files: PlannedWrite[];
  env: { added: string[]; kept: string[]; changed: string[] };
  contractHash: string;
  contractHashWarning?: string;
  contractChanged?: { from: string; to: string; note: string };
  pinnedVersion: string | null;
  /** Why the artifact was left unpinned, when it could have been pinned. */
  pinNote?: string;
  lock: { path: string; migrated: boolean; legacySources: string[]; note?: string };
  usage: string;
  evidenceLevel: string;
}

/**
 * Resolve everything that does not need the network (framework, language,
 * alias, paths) first, so a bad path or alias fails before any request.
 */
function planTarget(writer: ConfinedWriter, input: BakeInput, fallbackName: string | null) {
  const detection = writer.inline ? null : detectStack(writer.root);
  let framework: Framework = input.framework ?? detection?.framework ?? (input.language === 'python' ? 'plain-python' : 'plain-ts');
  // An explicit language that disagrees with the detected framework wins, with the plain adapter for that language.
  if (input.language && languageOf(framework) !== input.language) framework = input.language === 'python' ? 'plain-python' : 'plain-ts';
  const language = languageOf(framework);
  const outDir = normalizeRel(input.outDir ?? defaultOutDir(framework, detection));
  writer.resolve(outDir); // confinement check, before any request
  const alias = input.alias ? assertAlias(input.alias) : fallbackName ? assertAlias(kebab(fallbackName, 'artifact').slice(0, 63).replace(/-+$/, '')) : null;
  return { detection, framework, language, outDir, alias };
}

/** What `swfte add` pins: the current published version when there is one (workflows only). */
async function resolvePin(
  client: SwfteClient,
  ref: string,
  contract: CatalogContract,
  wanted: boolean
): Promise<{ pinnedVersion: string | null; contract: CatalogContract; note?: string }> {
  if (parseCatalogRef(ref).kind !== 'workflow') return { pinnedVersion: null, contract };
  if (!wanted) return { pinnedVersion: null, contract, note: 'Unpinned (--no-pin): the client calls /invoke, so every new publish reaches this code immediately.' };
  const v = contract.version ?? null;
  const unpublished = `${ref} has no published version to pin yet, so the client calls /invoke (the latest published version). Publish it, then \`swfte upgrade\` pins it.`;
  if (!isPinnable(ref, v)) return { pinnedVersion: null, contract, note: unpublished };
  const found = await lookupPinnedVersion(client, ref, v, contract);
  switch (found.state) {
    case 'published':
      return { pinnedVersion: v, contract: found.contract };
    case 'not-published':
      return { pinnedVersion: null, contract, note: unpublished };
    case 'unsupported':
      return { pinnedVersion: null, contract, note: `Left unpinned: ${found.detail}. The client calls /invoke.` };
    case 'gone':
      throw new Error(`${found.detail}; nothing to pin.`);
  }
}

export async function bakeArtifact(ctx: BakeContext, input: BakeInput): Promise<BakeResult> {
  const { client, config, writer } = ctx;
  const r = parseCatalogRef(input.catalogRef);
  if (input.framework && !(FRAMEWORKS as readonly string[]).includes(input.framework)) {
    throw new LockError(`Unknown framework "${input.framework}". Use one of: ${FRAMEWORKS.join(', ')}.`);
  }
  const pre = planTarget(writer, input, null);
  if (input.alias) assertAlias(input.alias);

  // Read the lock before the network too: a conflicted lock should stop us early.
  const legacyDirs = [...new Set([pre.outDir, 'src/swfte', 'swfte'])];
  const loaded = loadLock(writer, { baseUrl: config.baseUrl, workspaceId: config.workspaceId ?? null }, { legacyDirs });
  if (loaded.exists && loaded.lock.baseUrl) assertLockBaseUrl(loaded.lock.baseUrl, ctx.env, config.baseUrl);

  const { detail, contract } = await fetchBoth(client, r.ref);
  // Re-adding an artifact without options keeps its existing alias, framework and directory.
  const existing = input.alias || input.framework || input.outDir
    ? null
    : loaded.lock.artifacts.find((a) => a.catalogRef === r.ref && (!input.language || a.language === input.language)) ?? null;
  const plan = existing
    ? planTarget(writer, { ...input, alias: existing.alias, framework: existing.framework, outDir: existing.outDir }, null)
    : planTarget(writer, input, detail.name || r.id);
  const alias = plan.alias!;
  const { framework, language, outDir } = plan;

  const taken = loaded.lock.artifacts.find((a) => a.alias === alias && a.language === language && a.catalogRef !== r.ref);
  if (taken && !input.force) {
    throw new LockError(`Alias "${alias}" (${language}) already names ${taken.catalogRef} in swfte.json. Pass a different alias, or force to repoint it.`);
  }

  const hashInfo = effectiveContractHash(contract);
  // The lock keeps the catalog contract's hash (what /v2/catalog/upgrades compares); the client is generated
  // from the pinned version's contract, whose invoke path names that version.
  const pin = await resolvePin(client, r.ref, contract, input.pin !== false);
  const spec = buildSpec(config, r.ref, alias, detail, pin.contract, hashInfo.hash, loaded.lock.baseUrl, ctx.env);
  const clientRel = normalizeRel(`${outDir}/${clientFileName(alias, language)}`);
  const clientAbs = writer.resolve(clientRel);
  // A client this tool generated for this artifact, unedited, is ours to regenerate; anything else needs force.
  const ours = (() => {
    if (writer.inline || !existsSync(clientAbs)) return false;
    const info = inspectGenerated(readFileSync(clientAbs, 'utf8'));
    return info.generated && info.catalogRef === r.ref && info.intact === true;
  })();
  writer.create(clientAbs, render(spec, language), input.force || ours);

  const adapter = planAdapter({
    framework,
    alias,
    catalogRef: r.ref,
    info: clientInfo(spec, language),
    clientPath: clientRel,
    outDir,
    appDir: plan.detection?.layout.appDir ?? (framework === 'nextjs' ? 'app' : null),
    esm: plan.detection?.layout.esm ?? false,
  });
  const adapterPaths: string[] = [];
  for (const f of adapter.files) {
    const abs = writer.resolve(f.path);
    if (f.ifMissing && !writer.inline && existsSync(abs)) continue;
    writer.create(abs, f.content, input.force);
    adapterPaths.push(normalizeRel(f.path));
  }

  const env = writer.mergeEnv(writer.resolve('.env.example'), CLIENT_ENV, { header: 'Swfte — read by generated clients (swfte add)' });

  const previousFiles = loaded.lock.artifacts.find((a) => a.alias === alias && a.language === language)?.files ?? [];
  const pinnedVersion = pin.pinnedVersion;
  const { lock, previous } = upsertArtifact(loaded.lock, {
    catalogRef: r.ref,
    alias,
    language,
    framework,
    outDir,
    contractHash: hashInfo.hash,
    pinnedVersion,
    // Keep files an earlier add recorded (e.g. an adapter the developer still has) unless they are gone.
    files: [...new Set([clientRel, ...adapterPaths, ...previousFiles.filter((f) => !writer.inline && safeExists(writer, f))])],
  });
  planLockWrite(writer, lock);
  const files = writer.commit();

  const changed = previous && previous.catalogRef === r.ref && !sameHash(previous.contractHash, hashInfo.hash);
  return {
    catalogRef: r.ref,
    alias,
    language,
    framework,
    outDir,
    detection: plan.detection ? { framework: plan.detection.framework, detected: plan.detection.detected, signals: plan.detection.signals } : null,
    files,
    env,
    contractHash: hashInfo.hash,
    ...(hashInfo.warning ? { contractHashWarning: hashInfo.warning } : {}),
    ...(changed
      ? { contractChanged: { from: previous!.contractHash, to: hashInfo.hash, note: 'The contract moved since the last add; review call sites against the regenerated types.' } }
      : {}),
    pinnedVersion,
    ...(pin.note ? { pinNote: pin.note } : {}),
    lock: {
      path: LOCK_FILE,
      migrated: loaded.migrated,
      legacySources: loaded.legacySources,
      ...(writer.inline
        ? { note: 'Hosted server: the returned swfte.json and .env.example hold only this artifact — merge them into the project\'s files rather than replacing them, or run `npx -p @swfte/mcp-server swfte add` in the repo.' }
        : {}),
    },
    usage: adapter.usage,
    evidenceLevel: detail.evidence?.level ?? 'unmeasured',
  };
}

function safeExists(writer: ConfinedWriter, rel: string): boolean {
  try {
    return existsSync(writer.resolve(rel));
  } catch {
    return false;
  }
}

/* ── upgrades ────────────────────────────────────────────────────────────── */

export interface UpgradeItem {
  catalogRef: string;
  currentHash: string | null;
  latestHash: string | null;
  breaking: boolean;
  latestVersion: string | null;
  evidenceLevel: string | null;
  summary: string | null;
  capabilityChanges: string[];
  requiresReapproval: boolean;
  /** The pinned ref no longer resolves (deleted, moved out of the workspace). */
  vanished: boolean;
}

/** The upgrades answer could not be trusted: truncated, not JSON, or not the documented shape. */
export class UpgradesUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'UpgradesUnavailableError';
  }
}

/**
 * A boolean flag from the upgrades answer, read fail-closed (BT-N10): only an
 * explicit false (false, "false", 0, "0", "no", null/absent) is false. `"true"`,
 * `1` and anything unrecognised are true — for "breaking" and
 * "requiresReapproval" a guess must hold the change, not wave it through.
 */
export function flagOf(v: unknown): boolean {
  if (v === undefined || v === null || v === false || v === 0) return false;
  if (typeof v === 'string' && /^\s*(false|0|no|off|)\s*$/i.test(v)) return false;
  return true;
}

/** Backend verdict that the pinned ref no longer resolves for this workspace (deleted, moved, never visible). */
function isVanished(it: Record<string, unknown>): boolean {
  if (flagOf(it.notFound) || flagOf(it.vanished)) return true;
  const status = String(it.status ?? '').toLowerCase();
  if (status === 'not_found' || status === 'gone' || status === '404') return true;
  return it.latestHash == null && /^\s*(not found|not a catalogref|gone|deleted)\b/i.test(String(it.summary ?? ''));
}

/**
 * GET /v2/catalog/upgrades?refs=<catalogRef:contractHash>,… — batched so a big lock never builds an oversized URL.
 *
 * The answer is validated, not trusted (BT-N2): a 200 whose body is truncated,
 * not JSON, or not `{ items: [{ catalogRef, … }] }` throws
 * UpgradesUnavailableError, so a proxy that cuts the response short turns the
 * gate "could not check", never green.
 */
export async function fetchUpgrades(client: SwfteClient, pins: Array<{ catalogRef: string; contractHash: string }>): Promise<Map<string, UpgradeItem>> {
  const out = new Map<string, UpgradeItem>();
  const unique = [...new Map(pins.map((p) => [`${p.catalogRef}:${p.contractHash}`, p])).values()];
  for (let i = 0; i < unique.length; i += 25) {
    const chunk = unique.slice(i, i + 25);
    const res: unknown = await client.request<unknown>({
      method: 'GET',
      path: '/v2/catalog/upgrades',
      query: { refs: chunk.map((p) => `${p.catalogRef}:${p.contractHash}`).join(',') },
    });
    if (!res || typeof res !== 'object' || Array.isArray(res)) {
      const shown = typeof res === 'string' ? `unparseable text "${res.slice(0, 60)}${res.length > 60 ? '…' : ''}"` : JSON.stringify(res ?? null);
      throw new UpgradesUnavailableError(`Swfte's upgrades answer was not a JSON object (got ${shown}); it may have been truncated.`);
    }
    const items = (res as { items?: unknown }).items;
    if (!Array.isArray(items)) throw new UpgradesUnavailableError("Swfte's upgrades answer has no items array; it may have been truncated.");
    for (const raw of items) {
      if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new UpgradesUnavailableError("Swfte's upgrades answer holds an item that is not an object.");
      const it = raw as Record<string, unknown>;
      const ref = typeof it.catalogRef === 'string' ? it.catalogRef.trim() : '';
      if (!ref) throw new UpgradesUnavailableError("Swfte's upgrades answer holds an item without a catalogRef.");
      out.set(ref, {
        catalogRef: ref,
        currentHash: it.currentHash == null ? null : String(it.currentHash),
        latestHash: it.latestHash == null ? null : String(it.latestHash),
        breaking: flagOf(it.breaking),
        latestVersion: it.latestVersion == null ? null : String(it.latestVersion),
        evidenceLevel: it.evidenceLevel == null ? null : String(it.evidenceLevel),
        summary: it.summary == null ? null : String(it.summary),
        capabilityChanges: Array.isArray(it.capabilityChanges) ? it.capabilityChanges.map(String) : [],
        requiresReapproval: flagOf(it.requiresReapproval),
        vanished: isVanished(it),
      });
    }
  }
  return out;
}

/* ── verify ──────────────────────────────────────────────────────────────── */

export type ProblemKind = 'drift' | 'edited' | 'missing' | 'breaking' | 'reapproval' | 'vanished' | 'lock' | 'unreachable';

export interface VerifyProblem {
  kind: ProblemKind;
  alias: string | null;
  catalogRef: string | null;
  detail: string;
  fix: string;
}

export interface VerifyReport {
  ok: boolean;
  /** 0 in sync · 1 drift, breaking upgrade or re-approval pending · 2 could not verify (no lock, no credential, backend unreachable). */
  exitCode: 0 | 1 | 2;
  artifacts: number;
  problems: VerifyProblem[];
  warnings: string[];
  upgrades: UpgradeItem[];
  remoteChecked: boolean;
}

interface ClientFileState {
  rel: string;
  exists: boolean;
  content: string | null;
  error?: string;
}

/** The generated client file of a lock entry: the listed file carrying the generated marker for this ref. */
function clientFileOf(writer: ConfinedWriter, a: LockArtifact): ClientFileState {
  const expected = normalizeRel(`${a.outDir}/${clientFileName(a.alias, a.language)}`);
  const candidates = [...new Set([...a.files, expected])];
  for (const rel of candidates) {
    let abs: string;
    try {
      abs = writer.resolve(rel);
    } catch (err) {
      return { rel, exists: false, content: null, error: err instanceof Error ? err.message : String(err) };
    }
    if (!existsSync(abs)) continue;
    const content = readFileSync(abs, 'utf8');
    const info = inspectGenerated(content);
    if (info.generated && (info.catalogRef === null || info.catalogRef === a.catalogRef)) return { rel, exists: true, content };
  }
  return { rel: expected, exists: false, content: null };
}

/** Local drift only: files present, unedited, generated against the pinned hash. No network. */
export function checkLocal(writer: ConfinedWriter, lock: Lock): { problems: VerifyProblem[]; warnings: string[] } {
  const problems: VerifyProblem[] = [];
  const warnings: string[] = [];
  for (const a of lock.artifacts) {
    const base = { alias: a.alias, catalogRef: a.catalogRef };
    if (!a.catalogRef || !a.contractHash) {
      problems.push({ ...base, kind: 'lock', detail: `swfte.json entry "${a.alias}" is missing catalogRef or contractHash.`, fix: `Re-add it: swfte add ${a.catalogRef || '<kind>:<id>'} --alias ${a.alias} --force` });
      continue;
    }
    const c = clientFileOf(writer, a);
    if (c.error) {
      problems.push({ ...base, kind: 'lock', detail: `swfte.json lists a path outside the project: ${c.error}`, fix: 'Edit swfte.json so every path is inside the repository.' });
      continue;
    }
    if (!c.exists || c.content === null) {
      problems.push({ ...base, kind: 'missing', detail: `Generated client ${c.rel} is missing.`, fix: 'Run `swfte sync` to regenerate it (or remove the entry from swfte.json).' });
    } else {
      const info = inspectGenerated(c.content);
      if (!info.contractHash || !sameHash(info.contractHash, a.contractHash)) {
        problems.push({
          ...base,
          kind: 'drift',
          detail: `${c.rel} was generated against contract ${short(info.contractHash)} but swfte.json pins ${short(a.contractHash)}.`,
          fix: 'Run `swfte sync` and commit the regenerated client together with swfte.json.',
        });
      }
      if (info.intact === false) {
        problems.push({
          ...base,
          kind: 'edited',
          detail: `${c.rel} was edited by hand; the next sync would discard those edits.`,
          fix: 'Move custom logic into the adapter or your own module, then `swfte sync --force` to restore the generated file.',
        });
      } else if (info.intact === null) {
        warnings.push(`${c.rel} predates checksummed clients; run \`swfte sync\` once to add one.`);
      }
    }
    for (const f of a.files) {
      if (f === c.rel) continue;
      if (!safeExists(writer, f)) warnings.push(`${f} (listed for ${a.alias}) is missing; if you removed the adapter on purpose, drop it from swfte.json.`);
    }
  }
  return { problems, warnings };
}

const short = (h: string | null | undefined) => (h ? String(h).replace(/^sha256:/, '').slice(0, 12) : '(none)');

export async function verifyProject(
  ctx: { client: SwfteClient | null; config?: Pick<ServerConfig, 'baseUrl' | 'workspaceId'>; writer: ConfinedWriter },
  opts: { offline?: boolean } = {}
): Promise<VerifyReport> {
  const problems: VerifyProblem[] = [];
  const warnings: string[] = [];
  let loaded;
  try {
    loaded = loadLock(ctx.writer, { baseUrl: ctx.config?.baseUrl ?? '', workspaceId: ctx.config?.workspaceId ?? null });
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    return { ok: false, exitCode: 1, artifacts: 0, problems: [{ kind: 'lock', alias: null, catalogRef: null, detail, fix: 'Repair swfte.json.' }], warnings, upgrades: [], remoteChecked: false };
  }
  if (!loaded.exists) {
    return {
      ok: false,
      exitCode: 2,
      artifacts: 0,
      problems: [{ kind: 'lock', alias: null, catalogRef: null, detail: `No ${LOCK_FILE} at the project root.`, fix: 'Run `swfte add <catalogRef>` first, or run verify from the repository root.' }],
      warnings,
      upgrades: [],
      remoteChecked: false,
    };
  }
  if (loaded.migrated) warnings.push('swfte.json is in the pre-v1 shape; `swfte sync` rewrites it as v1.');
  const lock = loaded.lock;
  const local = checkLocal(ctx.writer, lock);
  problems.push(...local.problems);
  warnings.push(...local.warnings);

  let upgrades: UpgradeItem[] = [];
  let remoteChecked = false;
  let unreachable = false;
  const pinned = lock.artifacts.filter((a) => a.catalogRef && a.contractHash);
  if (!opts.offline && pinned.length) {
    if (!ctx.client) {
      unreachable = true;
      problems.push({ kind: 'unreachable', alias: null, catalogRef: null, detail: 'No credential: cannot ask Swfte about upgrades.', fix: 'Set SWFTE_API_KEY (or SWFTE_PAT) in CI, or pass --offline to check local drift only.' });
    } else {
      try {
        const map = await fetchUpgrades(ctx.client, pinned.map((a) => ({ catalogRef: a.catalogRef, contractHash: a.contractHash })));
        remoteChecked = true;
        upgrades = [...map.values()];
        const seen = new Set<string>();
        for (const a of pinned) {
          if (seen.has(a.catalogRef)) continue;
          seen.add(a.catalogRef);
          const u = map.get(a.catalogRef);
          const aliases = pinned.filter((x) => x.catalogRef === a.catalogRef).map((x) => x.alias);
          const alias = [...new Set(aliases)].join(',');
          if (!u || u.vanished) {
            // BT-N3: a pin whose artifact is gone is broken code in waiting, not a warning.
            problems.push({
              kind: 'vanished',
              alias,
              catalogRef: a.catalogRef,
              detail: `${a.catalogRef} is no longer available to this workspace (${u ? u.summary ?? 'not found' : 'Swfte returned nothing for it'}): it was deleted, unpublished or moved out of the workspace, so the code calling it will fail.`,
              fix: `Check the artifact in Studio and restore or re-share it; or re-point the code (\`swfte add <kind>:<id> --alias ${aliases[0]} --force\`); or remove it from swfte.json.`,
            });
            continue;
          }
          const moved = u.latestHash && !sameHash(u.latestHash, a.contractHash);
          if (u.requiresReapproval) {
            problems.push({
              kind: 'reapproval',
              alias,
              catalogRef: a.catalogRef,
              detail: `${a.catalogRef} changed capabilities${u.capabilityChanges.length ? `: ${u.capabilityChanges.join('; ')}` : ''} — it needs re-approval before this code should call it.`,
              fix: `Review the change in Studio, then \`swfte upgrade ${aliases[0]} --accept-capability-changes\` and commit.`,
            });
          }
          if (u.breaking) {
            problems.push({
              kind: 'breaking',
              alias,
              catalogRef: a.catalogRef,
              detail: `${a.catalogRef} has a breaking contract change pending (${u.summary ?? 'required input or output changed'}).`,
              fix: `\`swfte upgrade ${aliases[0]}\`, fix the call sites against the new types, and commit.`,
            });
          } else if (moved && !u.requiresReapproval) {
            warnings.push(`${a.catalogRef}: non-breaking upgrade available${u.latestVersion ? ` (${u.latestVersion})` : ''}${u.summary ? ` — ${u.summary}` : ''}. Run \`swfte sync\`.`);
          }
        }
      } catch (err) {
        unreachable = true;
        const detail =
          err instanceof SwfteApiError ? `${err.status} ${err.code}: ${err.message}` : err instanceof Error ? err.message : String(err);
        problems.push({ kind: 'unreachable', alias: null, catalogRef: null, detail: `Could not check upgrades: ${detail}`, fix: 'Retry, or pass --offline to check local drift only.' });
      }
      // Pinned versions: the version the code calls must still be published (BT-N3). One lookup per ref@version.
      const vanished = new Set(problems.filter((p) => p.kind === 'vanished').map((p) => p.catalogRef));
      const pins = new Map<string, LockArtifact[]>();
      for (const a of pinned) {
        if (!isPinnable(a.catalogRef, a.pinnedVersion) || vanished.has(a.catalogRef)) continue;
        const k = `${a.catalogRef}@${a.pinnedVersion}`;
        pins.set(k, [...(pins.get(k) ?? []), a]);
      }
      for (const group of pins.values()) {
        const a = group[0]!;
        const alias = [...new Set(group.map((x) => x.alias))].join(',');
        try {
          const found = await lookupPinnedVersion(ctx.client, a.catalogRef, a.pinnedVersion!, { catalogRef: a.catalogRef, invoke: { method: 'POST', path: '', auth: 'api_key', async: true, statusPath: null }, inputSchema: {}, outputSchema: {} });
          if (found.state === 'not-published' || found.state === 'gone') {
            problems.push({
              kind: 'vanished',
              alias,
              catalogRef: a.catalogRef,
              detail: `The pinned version the code calls is gone: ${found.detail}. Calls to it now fail (404).`,
              fix: `Re-publish that version, or move the pin: \`swfte upgrade ${group[0]!.alias}\`.`,
            });
          } else if (found.state === 'unsupported') {
            warnings.push(`${a.catalogRef}: could not confirm pinned version ${a.pinnedVersion} (${found.detail}).`);
          }
        } catch (err) {
          unreachable = true;
          const detail = err instanceof SwfteApiError ? `${err.status} ${err.code}: ${err.message}` : err instanceof Error ? err.message : String(err);
          problems.push({ kind: 'unreachable', alias, catalogRef: a.catalogRef, detail: `Could not check pinned version ${a.pinnedVersion}: ${detail}`, fix: 'Retry, or pass --offline to check local drift only.' });
        }
      }
    }
  }

  const failing = problems.some((p) => p.kind !== 'unreachable');
  const exitCode: 0 | 1 | 2 = failing ? 1 : unreachable ? 2 : 0;
  return { ok: exitCode === 0, exitCode, artifacts: lock.artifacts.length, problems, warnings, upgrades, remoteChecked };
}

/* ── sync / upgrade ──────────────────────────────────────────────────────── */

export type SyncStatus =
  | 'unchanged'
  | 'regenerated'
  | 'restored'
  | 'blocked-breaking'
  | 'blocked-reapproval'
  | 'blocked-edited'
  /** The contract moved but /v2/catalog/upgrades could not vet it (down, truncated, silent): held, pin unchanged (BT-N4). */
  | 'blocked-unvetted'
  /** `swfte upgrade` found no published version to move the pin to. */
  | 'blocked-unpublished'
  | 'error';

export interface SyncEntryResult {
  alias: string;
  language: Language;
  catalogRef: string;
  status: SyncStatus;
  from: string;
  to: string | null;
  diff: string | null;
  breakingReasons: string[];
  capabilityChanges: string[];
  message: string;
}

export interface SyncResult {
  dryRun: boolean;
  entries: SyncEntryResult[];
  files: PlannedWrite[];
  lock: { path: string; migrated: boolean; changed: boolean };
  summary: string;
}

export interface SyncOptions {
  /** Only these aliases. */
  aliases?: string[];
  dryRun?: boolean;
  /** Overwrite hand-edited clients. */
  force?: boolean;
  /** Take breaking changes (upgrade). */
  allowBreaking?: boolean;
  /** Take capability changes that need re-approval (upgrade --accept-capability-changes). */
  acceptCapabilityChanges?: boolean;
  /** Move a version pin to the current published version (upgrade). Plain sync never moves a pin. */
  movePin?: boolean;
  /** With movePin: false leaves an unpinned workflow unpinned (upgrade --no-pin). */
  pin?: boolean;
}

/**
 * Refetch every pinned contract; regenerate clients whose contract moved (or
 * whose file is missing). Breaking and re-approval changes are held back
 * unless explicitly accepted — that is what `swfte upgrade` is for — so a
 * routine sync can never silently change what the code is allowed to call.
 */
export async function syncProject(ctx: BakeContext, opts: SyncOptions = {}): Promise<SyncResult> {
  const { client, config, writer } = ctx;
  const loaded = loadLock(writer, { baseUrl: config.baseUrl, workspaceId: config.workspaceId ?? null });
  if (!loaded.exists) throw new LockError(`No ${LOCK_FILE} at the project root. Run \`swfte add <catalogRef>\` first.`);
  if (loaded.lock.baseUrl) assertLockBaseUrl(loaded.lock.baseUrl, ctx.env, config.baseUrl);
  let lock = loaded.lock;
  const wanted = opts.aliases?.length ? new Set(opts.aliases) : null;
  const targets = lock.artifacts.filter((a) => !wanted || wanted.has(a.alias));
  if (wanted) {
    const missing = [...wanted].filter((w) => !lock.artifacts.some((a) => a.alias === w));
    if (missing.length) throw new LockError(`No artifact with alias ${missing.map((m) => `"${m}"`).join(', ')} in swfte.json. Known: ${[...new Set(lock.artifacts.map((a) => a.alias))].join(', ') || '(none)'}.`);
  }

  // One upgrades call for server-side breaking/capability verdicts; a local shape diff is the fallback.
  let upgrades = new Map<string, UpgradeItem>();
  let upgradesError: string | null = null;
  try {
    upgrades = await fetchUpgrades(client, targets.map((a) => ({ catalogRef: a.catalogRef, contractHash: a.contractHash })));
  } catch (err) {
    upgradesError = err instanceof Error ? err.message : String(err);
  }

  const entries: SyncEntryResult[] = [];
  const cache = new Map<string, Promise<{ detail: CatalogEntryDetail; contract: CatalogContract }>>();
  for (const a of targets) {
    const base = { alias: a.alias, language: a.language, catalogRef: a.catalogRef, from: a.contractHash };
    try {
      if (!cache.has(a.catalogRef)) cache.set(a.catalogRef, fetchBoth(client, a.catalogRef));
      const { detail, contract } = await cache.get(a.catalogRef)!;
      const hashInfo = effectiveContractHash(contract);
      const moved = !sameHash(a.contractHash, hashInfo.hash);
      const pinVersion = isPinnable(a.catalogRef, a.pinnedVersion) ? a.pinnedVersion : null;
      const pinned = pinVersion !== null;
      const current = clientFileOf(writer, a);
      if (current.error) throw new LockError(current.error);
      const info = current.content ? inspectGenerated(current.content) : null;
      const edited = info?.intact === false;
      const target = () => writer.resolve(current.exists ? current.rel : normalizeRel(`${a.outDir}/${clientFileName(a.alias, a.language)}`));

      // A pinned artifact keeps calling its version however far upstream moves; only `swfte upgrade` moves
      // the pin. Sync still restores or regenerates the client for the pinned version itself.
      if (pinned && (!moved || !opts.movePin)) {
        let pinnedContract: CatalogContract;
        if (!moved) {
          pinnedContract = pinContract(contract, parseCatalogRef(a.catalogRef).id, pinVersion!);
        } else {
          const found = await lookupPinnedVersion(client, a.catalogRef, pinVersion!, contract);
          if (found.state === 'unsupported' && current.exists && !edited) {
            // Cannot re-derive the pinned client here; the one on disk is still the pinned version's.
            entries.push({ ...base, status: 'unchanged', to: a.contractHash, diff: null, breakingReasons: [], capabilityChanges: [], message: `Pinned to ${pinVersion}; kept as is (${found.detail}). A newer version is published; \`swfte upgrade ${a.alias}\` moves the pin.` });
            continue;
          }
          if (found.state !== 'published') throw new Error(`Pinned version ${a.pinnedVersion} of ${a.catalogRef} is unavailable (${found.detail}). Run \`swfte upgrade ${a.alias}\` to move the pin.`);
          pinnedContract = found.contract;
        }
        const spec = buildSpec(config, a.catalogRef, a.alias, detail, pinnedContract, a.contractHash, lock.baseUrl, ctx.env);
        const content = render(spec, a.language);
        const newer = moved ? ` A newer version${contract.version ? ` (${contract.version})` : ''} is published; \`swfte upgrade ${a.alias}\` moves the pin.` : '';
        if (current.content === content) {
          entries.push({ ...base, status: 'unchanged', to: a.contractHash, diff: null, breakingReasons: [], capabilityChanges: [], message: `Pinned to ${a.pinnedVersion}; up to date.${newer}` });
          continue;
        }
        if (edited && !opts.force) {
          entries.push({ ...base, status: 'blocked-edited', to: a.contractHash, diff: null, breakingReasons: [], capabilityChanges: [], message: `${current.rel} was edited by hand; pass force to replace it with the generated file.${newer}` });
          continue;
        }
        const abs = target();
        writer.create(abs, content, true);
        const rel = writer.rel(abs);
        lock = upsertArtifact(lock, { ...a, files: [...new Set([rel, ...a.files])] }).lock;
        entries.push({
          ...base,
          status: current.exists ? 'regenerated' : 'restored',
          to: a.contractHash,
          diff: null,
          breakingReasons: [],
          capabilityChanges: [],
          message: `${current.exists ? 'Regenerated' : 'Restored'} ${rel} for pinned version ${a.pinnedVersion}.${newer}`,
        });
        continue;
      }

      // Unpinned, or `swfte upgrade` moving the pin: the client follows the latest published contract.
      let nextPin: string | null = null;
      let clientContract = contract;
      // upgrade pins the current published version (also for an artifact first added before it was published).
      if (pinned || (opts.movePin && opts.pin !== false && parseCatalogRef(a.catalogRef).kind === 'workflow')) {
        const v = contract.version ?? null;
        const found = isPinnable(a.catalogRef, v) ? await lookupPinnedVersion(client, a.catalogRef, v, contract) : null;
        if (found?.state === 'published') {
          nextPin = v;
          clientContract = found.contract;
        } else if (pinned) {
          entries.push({ ...base, status: 'blocked-unpublished', to: hashInfo.hash, diff: null, breakingReasons: [], capabilityChanges: [], message: `The latest contract of ${a.catalogRef} is not a published version${found ? ` (${found.detail})` : ''}; the pin stays at ${a.pinnedVersion}. Publish it, then rerun \`swfte upgrade ${a.alias}\`.` });
          continue;
        }
      }
      const spec = buildSpec(config, a.catalogRef, a.alias, detail, clientContract, hashInfo.hash, lock.baseUrl, ctx.env);
      const content = render(spec, a.language);
      const oldShape = current.content ? readShape(current.content) : null;
      const diff: ShapeDiff | null = oldShape ? diffShapes(oldShape, specShape(spec)) : null;
      const u = upgrades.get(a.catalogRef);
      const diffText = moved ? (diff ? describeDiff(diff) : (u?.summary ?? 'contract changed (no previous shape recorded to diff against)')) : null;

      // BT-N4: a moved contract is taken only after the server vetted it. With the upgrades check down,
      // truncated or silent about this ref, re-approval is unknown — hold it rather than re-pin past the gate.
      if (moved && (upgradesError !== null || !u || u.vanished)) {
        const why = upgradesError !== null ? `upgrade check unavailable: ${upgradesError}` : u?.vanished ? `Swfte reports ${a.catalogRef} ${u.summary ?? 'not found'}` : `Swfte returned no upgrade verdict for ${a.catalogRef}`;
        entries.push({ ...base, status: 'blocked-unvetted', to: hashInfo.hash, diff: diffText, breakingReasons: [], capabilityChanges: [], message: `Contract moved but could not be vetted for breaking or capability changes (${why}). Nothing changed; rerun \`swfte sync\` when the check answers.` });
        continue;
      }
      // Fail closed: breaking when either the server or the local shape diff says so.
      const breaking = moved && (Boolean(u?.breaking) || Boolean(diff?.breaking));
      const reapproval = moved && Boolean(u?.requiresReapproval);
      const capabilityChanges = u?.capabilityChanges ?? [];
      const breakingReasons = [...new Set([...(diff?.reasons ?? []), ...(u?.breaking ? [u.summary ?? 'server reports a breaking change'] : [])])];

      if (moved && reapproval && !opts.acceptCapabilityChanges) {
        entries.push({ ...base, status: 'blocked-reapproval', to: hashInfo.hash, diff: diffText, breakingReasons, capabilityChanges, message: `Capability changes need re-approval (${capabilityChanges.join('; ') || 'see Studio'}). Review, then \`swfte upgrade ${a.alias} --accept-capability-changes\`.` });
        continue;
      }
      if (moved && breaking && !opts.allowBreaking) {
        entries.push({ ...base, status: 'blocked-breaking', to: hashInfo.hash, diff: diffText, breakingReasons, capabilityChanges, message: `Breaking change held back (${breakingReasons.join('; ') || 'see summary'}). Run \`swfte upgrade ${a.alias}\` and fix call sites.` });
        continue;
      }
      if (edited && !opts.force && (moved || current.content !== content)) {
        entries.push({ ...base, status: 'blocked-edited', to: hashInfo.hash, diff: diffText, breakingReasons, capabilityChanges, message: `${current.rel} was edited by hand; pass force to replace it with the generated file.` });
        continue;
      }
      const abs = target();
      // The file is ours (generated marker, intact or forced), so replacing it is not an overwrite of user work.
      writer.create(abs, content, true);
      const rel = writer.rel(abs);
      const pinMoved = nextPin !== null && nextPin !== a.pinnedVersion;
      const status: SyncStatus = !current.exists ? 'restored' : moved || pinMoved || current.content !== content ? 'regenerated' : 'unchanged';
      lock = upsertArtifact(lock, {
        ...a,
        contractHash: hashInfo.hash,
        pinnedVersion: nextPin ?? (parseCatalogRef(a.catalogRef).kind === 'workflow' ? null : a.pinnedVersion),
        files: [...new Set([rel, ...a.files])],
      }).lock;
      const pinText = pinMoved ? ` Pin moved ${a.pinnedVersion} → ${nextPin}.` : '';
      entries.push({
        ...base,
        status,
        to: hashInfo.hash,
        diff: diffText,
        breakingReasons: breaking ? breakingReasons : [],
        capabilityChanges,
        message:
          status === 'unchanged'
            ? 'Up to date.'
            : status === 'restored'
              ? `Restored missing ${rel}.${pinText}`
              : moved
                ? `Regenerated ${rel}: ${diffText}.${pinText}${hashInfo.warning ? ` ${hashInfo.warning}` : ''}`
                : `Regenerated ${rel}${pinText || ' (generator output changed; contract unchanged)'}.`,
      });
    } catch (err) {
      entries.push({ ...base, status: 'error', to: null, diff: null, breakingReasons: [], capabilityChanges: [], message: err instanceof Error ? err.message : String(err) });
    }
  }

  const before = JSON.stringify(loaded.lock);
  const lockChanged = loaded.migrated || JSON.stringify(lock) !== before;
  if (lockChanged) planLockWrite(writer, lock);
  const files = opts.dryRun ? [] : writer.commit();
  const count = (s: SyncStatus) => entries.filter((e) => e.status === s).length;
  const summary =
    `${entries.length} artifact(s): ${count('unchanged')} unchanged, ${count('regenerated')} regenerated, ${count('restored')} restored` +
    `${count('blocked-breaking') ? `, ${count('blocked-breaking')} held back (breaking)` : ''}` +
    `${count('blocked-reapproval') ? `, ${count('blocked-reapproval')} held back (re-approval)` : ''}` +
    `${count('blocked-edited') ? `, ${count('blocked-edited')} held back (hand-edited)` : ''}` +
    `${count('blocked-unvetted') ? `, ${count('blocked-unvetted')} held back (could not be vetted)` : ''}` +
    `${count('blocked-unpublished') ? `, ${count('blocked-unpublished')} held back (not published)` : ''}` +
    `${count('error') ? `, ${count('error')} failed` : ''}` +
    `${upgradesError ? ` (upgrade check unavailable: ${upgradesError}; breaking judged from local shape diff)` : ''}` +
    `${opts.dryRun ? ' — dry run, nothing written' : ''}.`;
  return { dryRun: Boolean(opts.dryRun), entries, files, lock: { path: LOCK_FILE, migrated: loaded.migrated, changed: lockChanged }, summary };
}

/** `swfte upgrade <alias>`: sync one alias, accepting a breaking change; capability changes still need explicit acceptance. */
export function upgradeAlias(ctx: BakeContext, alias: string, opts: { acceptCapabilityChanges?: boolean; force?: boolean; dryRun?: boolean; pin?: boolean } = {}) {
  return syncProject(ctx, { aliases: [alias], allowBreaking: true, movePin: true, pin: opts.pin, acceptCapabilityChanges: opts.acceptCapabilityChanges, force: opts.force, dryRun: opts.dryRun });
}

/* ── dev fixtures ────────────────────────────────────────────────────────── */

/**
 * `swfte dev --record`: fetch each artifact's contract (the pinned version's,
 * when pinned) and keep it as `.swfte/fixtures/<alias>.<ts|py>.json` — schemas
 * and invoke block only, secret-checked like every other write — so `swfte dev`
 * serves full examples offline afterwards.
 */
export async function recordFixtures(ctx: BakeContext): Promise<PlannedWrite[]> {
  const { client, config, writer } = ctx;
  const loaded = loadLock(writer, { baseUrl: config.baseUrl, workspaceId: config.workspaceId ?? null });
  if (!loaded.exists) throw new LockError(`No ${LOCK_FILE} in the project root. Run \`swfte add <catalogRef>\` first.`);
  const cache = new Map<string, Promise<CatalogContract>>();
  for (const a of loaded.lock.artifacts) {
    const key = `${a.catalogRef}@${a.pinnedVersion ?? ''}`;
    if (!cache.has(key)) {
      cache.set(
        key,
        (async () => {
          const { contract } = await fetchBoth(client, a.catalogRef);
          if (!isPinnable(a.catalogRef, a.pinnedVersion)) return contract;
          const found = await lookupPinnedVersion(client, a.catalogRef, a.pinnedVersion, contract);
          if (found.state !== 'published') throw new Error(`Pinned version ${a.pinnedVersion} of ${a.catalogRef}: ${found.detail}.`);
          return found.contract;
        })()
      );
    }
    const c = await cache.get(key)!;
    const fixture = {
      catalogRef: a.catalogRef,
      alias: a.alias,
      pinnedVersion: isPinnable(a.catalogRef, a.pinnedVersion) ? a.pinnedVersion : null,
      invoke: c.invoke,
      inputSchema: c.inputSchema ?? null,
      outputSchema: c.outputSchema ?? null,
    };
    // Fixture files are ours: regenerated on every --record.
    writer.create(writer.resolve(fixturePath(a)), `${JSON.stringify(fixture, null, 2)}\n`, true);
  }
  return writer.commit();
}

export { LockError };
