/**
 * Reuse-first tools: ask Studio what already exists, and how well it is proven,
 * before generating anything.
 *
 * Generating a workflow costs tens of thousands of tokens and minutes of wall
 * time, and produces something with no run history. A catalog entry that has
 * already run a hundred times is cheaper and better evidenced. These tools make
 * that trade the first thing a coding agent sees.
 */
import { z } from 'zod';
import {
  CATALOG_KINDS,
  CatalogRefArg,
  EVIDENCE_LEVELS,
  GENERATION_ESTIMATE,
  REUSABLE_LEVELS,
  getContextPackage,
  getEntry,
  interpretEvidence,
  ladderRank,
  parseCatalogRef,
  presentEvidence,
  provenanceLine,
  searchCatalog,
  type CatalogEntrySummary,
  type CatalogKind,
  type CatalogRef,
} from '../catalog.js';
import { referencesOf } from '../preflight/derive.mjs';
import type { SwfteClient } from '../client.js';
import { decisionOf, emitTelemetry } from '../telemetry.js';
import type { ToolDefinition } from './_types.js';

const DEGRADED_NOTES: Record<string, string> = {
  jev_rerank: 'semantic re-ranking (Jev) was unavailable, so order is lexical — weigh evidence level over position',
};

function reasonsFor(item: CatalogEntrySummary, query: string, facetFilter: Record<string, string | undefined>): string[] {
  const reasons: string[] = [];
  const q = query.trim().toLowerCase();
  if (q && item.name?.toLowerCase().includes(q)) reasons.push(`name matches "${query}"`);
  else if (q && item.description?.toLowerCase().includes(q)) reasons.push(`description matches "${query}"`);
  for (const [key, want] of Object.entries(facetFilter)) {
    if (!want) continue;
    const f = item.facets?.find((x) => x.key === key && x.value.toLowerCase() === want.toLowerCase());
    if (f) reasons.push(`${key}=${f.value} (${f.status.toLowerCase()}${f.confidence != null ? `, confidence ${f.confidence}` : ''})`);
  }
  const confirmed = (item.facets ?? []).filter((f) => f.status === 'CONFIRMED').map((f) => `${f.key}=${f.value}`);
  if (confirmed.length) reasons.push(`confirmed facets: ${confirmed.slice(0, 4).join(', ')}`);
  const ev = item.evidence;
  if (ev) {
    const runs = ev.runs ? `${ev.runs.succeeded}/${ev.runs.total} runs succeeded` : null;
    reasons.push(`evidence ${ev.level}${runs ? ` — ${runs}` : ''}`);
    for (const r of (ev.reasons ?? []).slice(0, 2)) reasons.push(r);
  }
  if (item.scope === 'public') reasons.push('public catalog entry (not from this workspace)');
  return reasons;
}

/**
 * A planning estimate of one wizard build of this kind — labelled as an estimate on the
 * wire, never measured, never a saving, and never added up (no running total exists
 * anywhere in this server). What reuse actually does is measured server-side from the
 * telemetry counts; see GET /v2/catalog/metrics.
 */
export const ESTIMATE_NOTE =
  'An estimate for one wizard build of this kind, not a measurement and not a saving. Do not add these up; ' +
  'measured reuse lives in Studio → Solution Hub → Insights.';

export function generationEstimate(kind: CatalogKind) {
  const e = GENERATION_ESTIMATE[kind];
  return e
    ? { estimate: true as const, tokens: e.tokens, seconds: e.seconds, basis: 'planning estimate for a wizard build of this kind; not measured for this workspace', note: ESTIMATE_NOTE }
    : { estimate: true as const, tokens: 0, seconds: 0, basis: `${kind} artifacts are not generated by a wizard, so reuse avoids no generation`, note: ESTIMATE_NOTE };
}

async function findExisting(
  client: SwfteClient,
  input: {
    query: string;
    kinds?: CatalogKind[];
    scope?: 'workspace' | 'public' | 'all';
    minEvidence?: string;
    facets?: { domain?: string; capability?: string; industry?: string };
    limit?: number;
    cursor?: string;
  }
) {
  const res = await searchCatalog(client, {
    query: input.query,
    kinds: input.kinds,
    scope: input.scope,
    minEvidence: input.minEvidence,
    domain: input.facets?.domain,
    capability: input.facets?.capability,
    industry: input.facets?.industry,
    limit: input.limit ?? 10,
    cursor: input.cursor,
  });

  const results = res.items.map((item, i) => ({
    rank: i + 1,
    catalogRef: item.catalogRef ?? `${item.kind}:${item.id}`,
    kind: item.kind,
    name: item.name,
    description: item.description ?? null,
    scope: item.scope,
    evidenceLevel: item.evidence?.level ?? 'unmeasured',
    successRate: item.evidence?.successRate ?? null,
    runs: item.evidence?.runs ?? null,
    // Rev 5: what the level rests on — independent workspaces, interval, freshness.
    independentWorkspaces: item.evidence?.independentWorkspaces ?? null,
    successRateInterval: item.evidence?.successRateInterval ?? null,
    freshness: item.evidence?.freshness ?? null,
    adopters: item.evidence?.adopters ?? null,
    // Rev 3: who made it and why, when the server projects it onto summaries.
    provenance: provenanceLine(item),
    license: item.license ?? (item.scope === 'public' ? null : 'proprietary'),
    updatedAt: item.updatedAt,
    reasons: reasonsFor(item, input.query, input.facets ?? {}),
    guidance: `Reuse catalogRef ${item.catalogRef ?? `${item.kind}:${item.id}`} via swfte_get_context before generating anything new.`,
  }));

  // Server order is the relevance order; the recommendation is the first result
  // whose evidence clears the reuse bar, falling back to the best on the ladder.
  const strong = results.find((r) => REUSABLE_LEVELS.has(r.evidenceLevel));
  const best =
    strong ??
    [...results]
      .filter((r) => r.evidenceLevel !== 'disputed')
      .sort((a, b) => ladderRank(b.evidenceLevel) - ladderRank(a.evidenceLevel) || a.rank - b.rank)[0];

  const degradedNotes = res.degraded.map((d) => `${d}: ${DEGRADED_NOTES[d] ?? 'subsystem unavailable; results may be less complete or less well ordered'}`);

  const recommendation = best
    ? {
        action: strong ? 'REUSE' : 'INSPECT_BEFORE_REUSE',
        catalogRef: best.catalogRef,
        name: best.name,
        evidenceLevel: best.evidenceLevel,
        why: interpretEvidence(best.evidenceLevel),
        nextStep: `Call swfte_get_context {catalogRef:"${best.catalogRef}"} for its contract, evidence and dependencies, then swfte_scaffold_client to bake it into the codebase.`,
        generationAvoidedEstimate: generationEstimate(best.kind),
      }
    : {
        action: 'BUILD',
        why: res.items.length
          ? 'Every match is disputed; building fresh is safer than reusing something that is failing.'
          : 'Nothing in the catalog matches. Building is justified.',
        nextStep: 'Call swfte_solution_advise (or swfte_composition_classify) to choose the form, then swfte_build.',
      };

  return {
    query: input.query,
    count: results.length,
    results,
    recommendation,
    degraded: res.degraded,
    ...(degradedNotes.length ? { degradedNotes } : {}),
    nextCursor: res.nextCursor,
    note:
      'Evidence levels are computed from recorded runs, evals and reviews, never asserted, and only independent ' +
      'workspaces raise them. "unmeasured" means no record exists — not that it fails. provenance is null when the ' +
      'search summary does not carry it; swfte_get_context always shows author, why, lineage and licence.',
  };
}

/* ── dependency tracing ──────────────────────────────────────────────────── */

const LIVE_PATH: Partial<Record<string, (id: string) => string>> = {
  workflow: (id) => `/v2/workflows/${encodeURIComponent(id)}`,
  agent: (id) => `/v2/agents/${encodeURIComponent(id)}`,
  chatflow: (id) => `/v2/chatflows/${encodeURIComponent(id)}`,
  widget: (id) => `/api/v2/widgets/${encodeURIComponent(id)}`,
  application: (id) => `/v2/applications/${encodeURIComponent(id)}`,
};

/** Kinds that can hold a reference to another artifact, i.e. candidates for "upstream". */
const REFERRING_KINDS: CatalogKind[] = ['workflow', 'agent', 'chatflow', 'widget', 'application', 'solution', 'module'];

interface Edge {
  from: string;
  to: string;
  relation: string;
  source: 'catalog' | 'live-graph';
}

async function liveReferences(client: SwfteClient, r: CatalogRef): Promise<Edge[]> {
  const path = LIVE_PATH[r.kind];
  if (!path) return [];
  try {
    const record = await client.request<unknown>({ method: 'GET', path: path(r.id), retries: 1 });
    return referencesOf(r.kind, record).map(([kind, id]) => ({
      from: r.ref,
      to: `${kind === 'dataset' ? 'dataset' : kind}:${id}`,
      relation: 'references',
      source: 'live-graph' as const,
    }));
  } catch {
    return [];
  }
}

async function traceDependencies(
  client: SwfteClient,
  input: { catalogRef: string; direction: 'downstream' | 'upstream'; depth?: number; maxScan?: number }
) {
  const root = parseCatalogRef(input.catalogRef);
  if (input.direction === 'downstream') {
    const maxDepth = input.depth ?? 2;
    const edges: Edge[] = [];
    const nodes = new Map<string, { catalogRef: string; name?: string; evidenceLevel?: string; depth: number }>();
    const errors: string[] = [];
    // Each node costs two reads; a wide graph is cut here and reported as truncated.
    const MAX_NODES = 60;
    let capped = false;
    let frontier: CatalogRef[] = [root];
    nodes.set(root.ref, { catalogRef: root.ref, depth: 0 });
    for (let depth = 0; depth < maxDepth && frontier.length; depth++) {
      const next: CatalogRef[] = [];
      for (const r of frontier) {
        let detailDeps: Edge[] = [];
        try {
          const d = await getEntry(client, r);
          const n = nodes.get(r.ref)!;
          n.name = d.name;
          n.evidenceLevel = d.evidence?.level;
          detailDeps = (d.dependencies ?? []).map((x) => ({ from: r.ref, to: x.catalogRef, relation: x.relation, source: 'catalog' as const }));
        } catch (err) {
          errors.push(`${r.ref}: ${err instanceof Error ? err.message : String(err)}`);
        }
        const live = await liveReferences(client, r);
        const seen = new Set(detailDeps.map((e) => e.to));
        for (const e of [...detailDeps, ...live.filter((e) => !seen.has(e.to))]) {
          edges.push(e);
          if (!nodes.has(e.to)) {
            if (nodes.size >= MAX_NODES) {
              capped = true;
              continue;
            }
            nodes.set(e.to, { catalogRef: e.to, depth: depth + 1 });
            try {
              next.push(parseCatalogRef(e.to));
            } catch {
              // A live reference to a kind the catalog does not index (e.g. dataset) is a leaf.
            }
          }
        }
      }
      frontier = next;
    }
    return {
      catalogRef: root.ref,
      direction: 'downstream',
      depth: maxDepth,
      nodes: [...nodes.values()],
      edges,
      truncated: frontier.length > 0 || capped,
      ...(errors.length ? { errors } : {}),
      note:
        '"catalog" edges come from the catalog entry\'s declared dependencies; "live-graph" edges are ids found in the ' +
        'artifact\'s own configuration (the same walk preflight uses). A live edge with no catalog edge means the ' +
        'catalog has not projected it yet.',
    };
  }

  // Upstream: the catalog has no reverse index, so scan referring entries in
  // this workspace and read their declared dependencies. Bounded and reported
  // as such — an unscanned referrer is unknown, not absent.
  const maxScan = input.maxScan ?? 40;
  const candidates: CatalogEntrySummary[] = [];
  let cursor: string | undefined;
  let degraded: string[] = [];
  do {
    const page = await searchCatalog(client, {
      query: '',
      kinds: REFERRING_KINDS,
      scope: 'workspace',
      limit: Math.min(50, maxScan - candidates.length),
      cursor,
    });
    degraded = [...new Set([...degraded, ...page.degraded])];
    candidates.push(...page.items);
    cursor = page.nextCursor ?? undefined;
  } while (cursor && candidates.length < maxScan);

  const dependents: Array<{ catalogRef: string; name: string; relation: string; evidenceLevel?: string }> = [];
  const errors: string[] = [];
  for (const c of candidates) {
    const ref = c.catalogRef ?? `${c.kind}:${c.id}`;
    if (ref === root.ref) continue;
    try {
      const d = await getEntry(client, parseCatalogRef(ref));
      const hit = (d.dependencies ?? []).find((x) => x.catalogRef === root.ref);
      if (hit) dependents.push({ catalogRef: ref, name: d.name, relation: hit.relation, evidenceLevel: d.evidence?.level });
    } catch (err) {
      errors.push(`${ref}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  return {
    catalogRef: root.ref,
    direction: 'upstream',
    dependents,
    scanned: candidates.length,
    truncated: Boolean(cursor),
    ...(degraded.length ? { degraded } : {}),
    ...(errors.length ? { errors } : {}),
    note:
      `Upstream is a bounded scan of ${candidates.length} workspace entries (maxScan ${maxScan}), not an index. ` +
      (cursor ? 'More entries exist — raise maxScan before concluding nothing else depends on this. ' : '') +
      'Changing this artifact affects every dependent listed; check their evidence after the change.',
  };
}

/* ── tools ───────────────────────────────────────────────────────────────── */

export const catalogTools: ToolDefinition[] = [
  {
    name: 'swfte_find_existing',
    title: 'Find proven artifacts before building',
    readOnly: true,
    description:
      'CALL THIS FIRST, before swfte_build or writing an integration by hand. Searches the Studio catalog ' +
      '(workflows, agents, chatflows, widgets, applications, MCP servers, models, modules, solutions) for ' +
      'something that already does the job, ranked, with each result\'s evidence level ' +
      `(${EVIDENCE_LEVELS.join(' | ')}), the reasons it matched, and an estimate of the generation it avoids. ` +
      'Returns a recommendation: REUSE (reuse catalogRef X via swfte_get_context), INSPECT_BEFORE_REUSE, or BUILD. ' +
      'Reports `degraded` subsystems (e.g. jev_rerank) instead of failing when classification is unavailable.',
    inputSchema: z.object({
      query: z.string().min(1).describe('What you need, in plain words ("invoice extraction", "support triage agent").'),
      kinds: z.array(z.enum(CATALOG_KINDS)).optional().describe('Restrict to these kinds.'),
      scope: z.enum(['workspace', 'public', 'all']).optional().describe('Default: server default (workspace + public).'),
      minEvidence: z.enum(EVIDENCE_LEVELS).optional().describe('Only return entries at or above this evidence level.'),
      facets: z
        .object({ domain: z.string().optional(), capability: z.string().optional(), industry: z.string().optional() })
        .optional()
        .describe('Facet filters (Jev-proposed or human-confirmed classifications).'),
      limit: z.number().int().min(1).max(50).optional(),
      cursor: z.string().optional().describe('nextCursor from a previous call.'),
    }),
    execute: async (input, ctx) => {
      const res = await findExisting(ctx.client, input);
      // Counts only: that a search happened and what the catalog recommended — never the query.
      emitTelemetry(ctx, { event: 'search' });
      const rec = res.recommendation as { action?: string; catalogRef?: string };
      const decision = decisionOf(rec.action);
      if (decision) emitTelemetry(ctx, { event: 'reuse_decision', decision, catalogRef: rec.catalogRef ?? null });
      return res;
    },
  },
  {
    name: 'swfte_get_context',
    title: 'Context package for a catalog artifact',
    readOnly: true,
    description:
      'Everything a coding agent needs before reusing an artifact, in one call: detail, invocation contract ' +
      '(method, path, auth, async/status path, input/output JSON Schemas, snippets, embed), evidence with ' +
      'its reasons and recent records, Jev facets (proposed vs confirmed), the stored composition rationale, ' +
      'reviews and dependencies, provenance (author, why, forkedFrom, licence) and evidence split into own vs ' +
      'independent runs (parentEvidence kept apart for forks), plus a contractHash for lock files and concrete next steps ' +
      '(swfte_scaffold_client / swfte_embed_widget). Use after swfte_find_existing.',
    inputSchema: z.object({
      catalogRef: CatalogRefArg,
      includeEvidenceRecords: z.boolean().optional().describe('Include the latest evidence records. Default true.'),
      includeSnippets: z.boolean().optional().describe('Include curl/TS/Python/MCP snippets. Default true.'),
    }),
    execute: async (input, { client }) => getContextPackage(client, parseCatalogRef(input.catalogRef), input),
  },
  {
    name: 'swfte_get_evidence',
    title: 'Evidence behind a catalog artifact',
    readOnly: true,
    description:
      'Why an artifact sits at its evidence level: run totals and success rate, evals, builder / domain-expert ' +
      'reviews, the reasons[] the level was computed from, and the latest evidence records (execution, eval, ' +
      'outcome, review). Levels are computed, never asserted — "unmeasured" means nothing was recorded, not that it works.',
    inputSchema: z.object({ catalogRef: CatalogRefArg }),
    execute: async (input, { client }) => {
      const r = parseCatalogRef(input.catalogRef);
      const d = await getEntry(client, r);
      return {
        catalogRef: r.ref,
        name: d.name,
        evidence: presentEvidence(d.evidence, d.parentEvidence),
        interpretation: interpretEvidence(d.evidence?.level),
        evidenceRecords: d.evidenceRecords ?? [],
        reviews: d.reviews ?? [],
        reusable: REUSABLE_LEVELS.has(d.evidence?.level ?? ''),
      };
    },
  },
  {
    name: 'swfte_trace_dependencies',
    title: 'Trace what an artifact depends on, or what depends on it',
    readOnly: true,
    description:
      'downstream: what this artifact needs (agents a workflow calls, knowledge a chatflow reads, the brain a ' +
      'widget binds), merged from catalog dependencies and the ids found in its live configuration — the same ' +
      'walk preflight uses. upstream: which workspace artifacts declare a dependency on it, via a bounded scan ' +
      '(reported as scanned/truncated, never as a complete answer). Run upstream before changing something others reuse.',
    inputSchema: z.object({
      catalogRef: CatalogRefArg,
      direction: z.enum(['downstream', 'upstream']),
      depth: z.number().int().min(1).max(4).optional().describe('downstream only. Default 2.'),
      maxScan: z.number().int().min(1).max(200).optional().describe('upstream only: entries to scan. Default 40.'),
    }),
    execute: async (input, { client }) => traceDependencies(client, input),
  },
];
