import { z } from 'zod';
import type { ToolDefinition } from './_types.js';
import { presentAction, type ActionRequest } from '../actions.js';

const provisioning=z.object({actionId:z.enum(['aws.s3.ensureBucket','aws.ses.ensureIdentity','aws.dynamodb.ensureTable']),cloudConnectionId:z.string().min(1).max(200),region:z.string().regex(/^[a-z]{2}-[a-z]+-[0-9]$/),params:z.object({purpose:z.string().min(1).max(100),email:z.string().email().optional(),domain:z.string().max(253).optional(),keyName:z.string().max(100).optional(),keyType:z.enum(['S','N','B']).optional()}).strict()}).strict();
export const cloudLinkTools:ToolDefinition[]=[
  {name:'swfte_aws_link',title:'Start AWS role link',description:'Generate a server-owned workspace ExternalId and a least-privilege role template. PENDING is not ACTIVE; customer installation and a successful server AssumeRole probe are required.',inputSchema:z.object({packs:z.array(z.enum(['STORAGE','MESSAGING','DATA'])).min(1).max(3),region:z.string().regex(/^[a-z]{2}-[a-z]+-[0-9]$/),displayName:z.string().min(1).max(100)}).strict(),execute:(input,{client})=>client.request({method:'POST',path:'/v1/cloud-connections/aws/link',body:input,retries:0})},
  {name:'swfte_aws_link_probe',title:'Probe AWS role link',description:'Run the actual server AssumeRole probe for the workspace-owned pending connection. Account id is validated by the server; no key or role credential is returned.',inputSchema:z.object({connectionId:z.string().min(1).max(200),accountId:z.string().regex(/^[0-9]{12}$/)}).strict(),execute:(input,{client})=>client.request({method:'POST',path:`/v1/cloud-connections/${encodeURIComponent(input.connectionId)}/probe`,body:{accountId:input.accountId},retries:0})},
  {name:'swfte_provision_plan',title:'Read exact cloud resource plan',readOnly:true,description:'Read the exact resource, region, cost estimate and action class before proposing consent. A collision requires a new plan and approval.',inputSchema:provisioning,execute:(input,{client})=>client.request({method:'POST',path:'/v2/provisioning/plans',body:input,retries:0})},
  {name:'swfte_provision_request',title:'Propose exact cloud provisioning consent',description:'Propose through the existing content-bound action queue. No resource is created here. A person approves in Studio; swfte_execute_approved_action then consumes that exact plan.',inputSchema:provisioning,execute:async(input,{client})=>presentAction(await client.request<ActionRequest>({method:'POST',path:'/v2/provisioning/consents',body:input,retries:0}))},
];
