import { z } from 'zod';
import { isDeepStrictEqual } from 'node:util';
import type { ToolDefinition, ToolContext } from './_types.js';
import {
  WidgetViewTypeEnum,
  WidgetBindingEnum,
  WidgetStateScopeEnum,
  WidgetBrainKindEnum,
  WidgetBindingSourceTypeEnum,
  UNRESOLVED_BINDING_SOURCE_TYPES,
} from '../contracts/backend-options.js';
const BASE='/api/v2/widgets', BINDINGS='/v1/widget-bindings';
const id=z.string().min(1).max(200);
const configuration=z.object({name:z.string().min(1).max(200).optional(),viewType:WidgetViewTypeEnum.optional(),binding:WidgetBindingEnum.optional(),dataBindingId:id.optional(),pullIntervalSeconds:z.number().int().min(1).max(86400).optional(),stateScope:WidgetStateScopeEnum.optional(),brain:z.object({kind:WidgetBrainKindEnum,id}).strict().optional()}).strict().refine(x=>Object.keys(x).length>0,'At least one supported configuration field is required');
const publicFields=['id','workspaceId','name','viewType','binding','dataBindingId','pullIntervalSeconds','stateScope','brain','active','deploymentId','jwksKeyId'];
const project=(value:any,fields=publicFields)=>Object.fromEntries(fields.filter(k=>value?.[k]!==undefined).map(k=>[k,value[k]]));
const bindingFields=['id','workspaceId','sourceType','createdAt'];
const studioSources=['S01','S03','S06','HEALTH','DATA_QUALITY'];
const bindingMetadata=(value:any)=>({...project(value,bindingFields),...(value?.sourceType==='STUDIO_OPERATIONS'&&studioSources.includes(value.sourceRef)?{sourceRef:value.sourceRef}:{})});
function retained(saved:any,expected:Record<string,unknown>){const mismatched=Object.keys(expected).filter(k=>!isDeepStrictEqual(saved?.[k],expected[k]));if(mismatched.length)throw Error(`WIDGET_READBACK_MISMATCH: ${mismatched.join(', ')}. The write may have partially persisted; inspect before retrying.`);}
function identity(value:any, expectedId:string|undefined, client:any){if(!value?.id||!value?.workspaceId)throw Error('WIDGET_READBACK_MISMATCH: missing scoped identity');if(expectedId&&value.id!==expectedId)throw Error('WIDGET_READBACK_MISMATCH: identity mismatch');if(client.credentialKind==='api-key'&&client.configuredWorkspaceId&&String(value.workspaceId)!==String(client.configuredWorkspaceId))throw Error('WIDGET_READBACK_MISMATCH: workspace mismatch');}
const bindingSchema=z.object({sourceType:WidgetBindingSourceTypeEnum,sourceRef:z.string().min(1).max(2000),query:z.string().max(20000).optional(),projection:z.string().max(10000).optional(),publicDataConfirmed:z.boolean().optional()}).strict().superRefine((v,c)=>{
 if(v.sourceType==='STUDIO_OPERATIONS'){if(!['S01','S03','S06','HEALTH','DATA_QUALITY'].includes(v.sourceRef))c.addIssue({code:'custom',message:'Unsupported Studio operations source'});if(v.query||v.projection)c.addIssue({code:'custom',message:'Studio operations uses its authenticated application renderer, not native query/projection'});}
 else {if(v.publicDataConfirmed!==true)c.addIssue({code:'custom',message:'Native source snapshots may be public: confirm explicitly that projected data is safe for public widget delivery'});try{const p=JSON.parse(v.projection||'');if(!p||Array.isArray(p)||Object.keys(p).length!==1||typeof p.key!=='string'||!p.key.trim())throw Error();}catch{c.addIssue({code:'custom',message:'Native projection supports only a JSON object with one nonempty key field; unsupported projections silently pass raw data through and are refused'});}}
 if(v.sourceType==='HTTP'){try{const u=new URL(v.sourceRef);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error();}catch{c.addIssue({code:'custom',message:'HTTP sources require HTTPS without credentials, query secrets or fragments'});}if(v.query)c.addIssue({code:'custom',message:'HTTP adapter does not consume query'});}
 if(v.sourceType==='DATASOURCE'&&!v.query?.trim())c.addIssue({code:'custom',message:'DATASOURCE requires a configured datasource ID and read-only query'});
});
export const widgetTools:ToolDefinition[]=[
 {name:'swfte_widgets_configure',title:'Configure a saved graphical or conversational widget',description:'Update supported display and source/brain fields on an existing widget, then verify every supplied field was persisted. Does not publish or establish source execution. FORM/MIXED input persistence requires a configured Studio renderer; stateScope is not a workspace ACL. For active widgets review configuration impact before updating.',inputSchema:z.object({widgetId:id,configuration}).strict(),execute:async(raw,{client})=>{const input=z.object({widgetId:id,configuration}).strict().parse(raw);const path=`${BASE}/${encodeURIComponent(input.widgetId)}`;const before:any=await client.request({method:'GET',path,retries:1});identity(before,input.widgetId,client);await client.request({method:'PUT',path,body:input.configuration,retries:0});const saved=await client.request({method:'GET',path,retries:1});identity(saved,input.widgetId,client);retained(saved,{...input.configuration,workspaceId:before.workspaceId});return {persisted:true,widget:project(saved),runtimeVerified:false};}},
 {name:'swfte_widget_bindings_list',title:'List widget data bindings',readOnly:true,description:'List authenticated workspace binding definitions, not source rows. Only HTTP and DATASOURCE register a WidgetDataSourceAdapter, so only those two resolve on a PULL/HYBRID read. STUDIO_OPERATIONS bindings persist (the widget wizard writes them) and resolve no rows: agents-service keeps no operations record store behind S01/S03/S06/HEALTH/DATA_QUALITY, so a PULL/HYBRID read returns sourceStatus UNAVAILABLE with a sourceUnavailableReason and serves the last stored snapshot if there is one. That is unavailable, not empty — the widget is not reporting that the workspace has no records, and live rows come only from the authenticated Studio renderer. MODULE and EXECUTION appear in the WidgetDataBinding javadoc but have no adapter and are not offered for creation.',inputSchema:z.object({}).strict(),execute:async(_,{client})=>{const rows=await client.request<any>({method:'GET',path:BINDINGS,retries:1});if(!Array.isArray(rows))throw Error('Unexpected widget binding list response');return rows.map(r=>{identity(r,undefined,client);const meta=bindingMetadata(r);return UNRESOLVED_BINDING_SOURCE_TYPES.includes(String(r?.sourceType))?{...meta,pullResolves:false,pullNote:'This sourceType resolves no live rows: a PULL/HYBRID read reports sourceStatus UNAVAILABLE with a reason and falls back to the last stored snapshot. Unavailable, not empty.'}:{...meta,pullResolves:true};});}},
 {name:'swfte_widget_bindings_get',title:'Inspect a widget data binding',readOnly:true,description:'Read scoped binding metadata without executing the source or returning raw rows, query parameters or credentials.',inputSchema:z.object({bindingId:id}).strict(),execute:async(input,{client})=>{const saved=await client.request({method:'GET',path:`${BINDINGS}/${encodeURIComponent(input.bindingId)}`,retries:1});identity(saved,input.bindingId,client);return bindingMetadata(saved);}},
 {name:'swfte_widget_bindings_create',title:'Create a widget data source definition',description:'Create then read back one native binding; attach its ID using swfte_widgets_configure. HTTP uses credential-free GET; DATASOURCE requires an existing configured source and read-only query. Native snapshots may be public, so require explicit publicDataConfirmed and a supported JSON projection {"key":"publicRows"}. This selects a top-level value only, not row/column redaction. Verify source output and read-only datasource permissions separately. Store credentials only in configured datasource/Vault/OAuth connections, never in sourceRef/query/projection. STUDIO_OPERATIONS sources S01/S03/S06/HEALTH/DATA_QUALITY require authenticated Studio rendering and do not become public by deployment. No source execution is claimed.',inputSchema:bindingSchema,execute:async(raw,{client})=>{const input=bindingSchema.parse(raw);const {publicDataConfirmed,...fields}=input;const body={...fields,...(input.sourceType==='STUDIO_OPERATIONS'?{paramsJson:JSON.stringify({access:'WORKSPACE',schemaVersion:1})}:{})};const created=await client.request<any>({method:'POST',path:BINDINGS,body,retries:0});if(!created?.id)throw Error('Binding create returned no ID; inspect list before retrying');const saved=await client.request<any>({method:'GET',path:`${BINDINGS}/${encodeURIComponent(created.id)}`,retries:1});identity(created,undefined,client);identity(saved,created.id,client);retained(saved,{...body,workspaceId:created.workspaceId});return {persisted:true,binding:bindingMetadata(saved),sourceExecutionVerified:false,access:input.sourceType==='STUDIO_OPERATIONS'?'WORKSPACE_RENDERER_REQUIRED':'PUBLIC_PROJECTION_REVIEWED'};}},
 {name:'swfte_widgets_lifecycle',title:'Pause, resume or rotate a widget signing key',description:'Operate an existing saved widget release using native pause/resume/jwks/rotate routes. Requires confirm:true and SWFTE_ALLOW_DEPLOY=1; without both returns a no-write preview. Reads saved status/key reference after the single mutation. This verifies persisted release state only, not that an already loaded embed stopped receiving data or that runtime access was revoked. Does not invent an embed endpoint or expose private signing keys. Resume needs an existing paused deployment; rotation keeps the previous key for the backend grace period.',inputSchema:z.object({widgetId:id,action:z.enum(['pause','resume','rotate']),confirm:z.boolean().optional()}).strict(),execute:async(input,{client,config}:ToolContext)=>{
 if(!input.confirm||!config.allowDeploy)return {executed:false,reason:!input.confirm?'CONFIRMATION_REQUIRED':'DEPLOY_DISABLED',action:input.action,widgetId:input.widgetId};
 const path=`${BASE}/${encodeURIComponent(input.widgetId)}`;const before:any=await client.request({method:'GET',path,retries:1});identity(before,input.widgetId,client);if(input.action!=='rotate'&&!before.deploymentId)throw Error('No current deployment to pause or resume');
 const result:any=await client.request({method:'POST',path:`${path}/${input.action==='rotate'?'jwks/rotate':input.action}`,retries:0});const saved:any=await client.request({method:'GET',path,retries:1});
 identity(saved,input.widgetId,client);retained(saved,{workspaceId:before.workspaceId,deploymentId:before.deploymentId});
 if(input.action==='rotate'){if(!result?.newKid||result.newKid===before.jwksKeyId||saved.jwksKeyId!==result.newKid)throw Error('WIDGET_READBACK_MISMATCH: new signing key reference was not retained; inspect before retrying');}
 else {if(!before.deploymentId)throw Error('WIDGET_READBACK_MISMATCH: no current deployment');const history:any=await client.request({method:'GET',path:`${path}/deployments`,retries:1});const rows=Array.isArray(history)?history:history?.content??[];const current=rows.find((r:any)=>(r.id??r.deploymentId)===saved.deploymentId);retained(current,{widgetId:input.widgetId,workspaceId:before.workspaceId,status:input.action==='resume'?'LIVE':'PAUSED'});}
 return {executed:true,action:input.action,widget:project(saved),runtimeVerified:false};
 }},
];
